// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: resource/definitions/chubo/chubo.proto

package chubo

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BootstrapStatusSpec describes bootstrap payload status.
type BootstrapStatusSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configured    bool                   `protobuf:"varint,1,opt,name=configured,proto3" json:"configured,omitempty"`
	Rendered      bool                   `protobuf:"varint,2,opt,name=rendered,proto3" json:"rendered,omitempty"`
	SignerSha256  string                 `protobuf:"bytes,3,opt,name=signer_sha256,json=signerSha256,proto3" json:"signer_sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapStatusSpec) Reset() {
	*x = BootstrapStatusSpec{}
	mi := &file_resource_definitions_chubo_chubo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapStatusSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapStatusSpec) ProtoMessage() {}

func (x *BootstrapStatusSpec) ProtoReflect() protoreflect.Message {
	mi := &file_resource_definitions_chubo_chubo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapStatusSpec.ProtoReflect.Descriptor instead.
func (*BootstrapStatusSpec) Descriptor() ([]byte, []int) {
	return file_resource_definitions_chubo_chubo_proto_rawDescGZIP(), []int{0}
}

func (x *BootstrapStatusSpec) GetConfigured() bool {
	if x != nil {
		return x.Configured
	}
	return false
}

func (x *BootstrapStatusSpec) GetRendered() bool {
	if x != nil {
		return x.Rendered
	}
	return false
}

func (x *BootstrapStatusSpec) GetSignerSha256() string {
	if x != nil {
		return x.SignerSha256
	}
	return ""
}

// OpenBaoJobStatusSpec describes OpenBao job status.
type OpenBaoJobStatusSpec struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Configured     bool                   `protobuf:"varint,1,opt,name=configured,proto3" json:"configured,omitempty"`
	Mode           string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	JobId          string                 `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	NomadReachable bool                   `protobuf:"varint,4,opt,name=nomad_reachable,json=nomadReachable,proto3" json:"nomad_reachable,omitempty"`
	Present        bool                   `protobuf:"varint,5,opt,name=present,proto3" json:"present,omitempty"`
	LastError      string                 `protobuf:"bytes,6,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OpenBaoJobStatusSpec) Reset() {
	*x = OpenBaoJobStatusSpec{}
	mi := &file_resource_definitions_chubo_chubo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenBaoJobStatusSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenBaoJobStatusSpec) ProtoMessage() {}

func (x *OpenBaoJobStatusSpec) ProtoReflect() protoreflect.Message {
	mi := &file_resource_definitions_chubo_chubo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenBaoJobStatusSpec.ProtoReflect.Descriptor instead.
func (*OpenBaoJobStatusSpec) Descriptor() ([]byte, []int) {
	return file_resource_definitions_chubo_chubo_proto_rawDescGZIP(), []int{1}
}

func (x *OpenBaoJobStatusSpec) GetConfigured() bool {
	if x != nil {
		return x.Configured
	}
	return false
}

func (x *OpenBaoJobStatusSpec) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *OpenBaoJobStatusSpec) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *OpenBaoJobStatusSpec) GetNomadReachable() bool {
	if x != nil {
		return x.NomadReachable
	}
	return false
}

func (x *OpenBaoJobStatusSpec) GetPresent() bool {
	if x != nil {
		return x.Present
	}
	return false
}

func (x *OpenBaoJobStatusSpec) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

// OpenGyozaStatusSpec describes opengyoza status.
type OpenGyozaStatusSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configured    bool                   `protobuf:"varint,1,opt,name=configured,proto3" json:"configured,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Running       bool                   `protobuf:"varint,3,opt,name=running,proto3" json:"running,omitempty"`
	Healthy       bool                   `protobuf:"varint,4,opt,name=healthy,proto3" json:"healthy,omitempty"`
	BinaryMode    string                 `protobuf:"bytes,5,opt,name=binary_mode,json=binaryMode,proto3" json:"binary_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenGyozaStatusSpec) Reset() {
	*x = OpenGyozaStatusSpec{}
	mi := &file_resource_definitions_chubo_chubo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenGyozaStatusSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenGyozaStatusSpec) ProtoMessage() {}

func (x *OpenGyozaStatusSpec) ProtoReflect() protoreflect.Message {
	mi := &file_resource_definitions_chubo_chubo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenGyozaStatusSpec.ProtoReflect.Descriptor instead.
func (*OpenGyozaStatusSpec) Descriptor() ([]byte, []int) {
	return file_resource_definitions_chubo_chubo_proto_rawDescGZIP(), []int{2}
}

func (x *OpenGyozaStatusSpec) GetConfigured() bool {
	if x != nil {
		return x.Configured
	}
	return false
}

func (x *OpenGyozaStatusSpec) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *OpenGyozaStatusSpec) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *OpenGyozaStatusSpec) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *OpenGyozaStatusSpec) GetBinaryMode() string {
	if x != nil {
		return x.BinaryMode
	}
	return ""
}

// OpenWontonStatusSpec describes openwonton status.
type OpenWontonStatusSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configured    bool                   `protobuf:"varint,1,opt,name=configured,proto3" json:"configured,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Running       bool                   `protobuf:"varint,3,opt,name=running,proto3" json:"running,omitempty"`
	Healthy       bool                   `protobuf:"varint,4,opt,name=healthy,proto3" json:"healthy,omitempty"`
	BinaryMode    string                 `protobuf:"bytes,5,opt,name=binary_mode,json=binaryMode,proto3" json:"binary_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenWontonStatusSpec) Reset() {
	*x = OpenWontonStatusSpec{}
	mi := &file_resource_definitions_chubo_chubo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenWontonStatusSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenWontonStatusSpec) ProtoMessage() {}

func (x *OpenWontonStatusSpec) ProtoReflect() protoreflect.Message {
	mi := &file_resource_definitions_chubo_chubo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenWontonStatusSpec.ProtoReflect.Descriptor instead.
func (*OpenWontonStatusSpec) Descriptor() ([]byte, []int) {
	return file_resource_definitions_chubo_chubo_proto_rawDescGZIP(), []int{3}
}

func (x *OpenWontonStatusSpec) GetConfigured() bool {
	if x != nil {
		return x.Configured
	}
	return false
}

func (x *OpenWontonStatusSpec) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *OpenWontonStatusSpec) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *OpenWontonStatusSpec) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *OpenWontonStatusSpec) GetBinaryMode() string {
	if x != nil {
		return x.BinaryMode
	}
	return ""
}

var File_resource_definitions_chubo_chubo_proto protoreflect.FileDescriptor

const file_resource_definitions_chubo_chubo_proto_rawDesc = "" +
	"\n" +
	"&resource/definitions/chubo/chubo.proto\x12 talos.resource.definitions.chubo\"v\n" +
	"\x13BootstrapStatusSpec\x12\x1e\n" +
	"\n" +
	"configured\x18\x01 \x01(\bR\n" +
	"configured\x12\x1a\n" +
	"\brendered\x18\x02 \x01(\bR\brendered\x12#\n" +
	"\rsigner_sha256\x18\x03 \x01(\tR\fsignerSha256\"\xc3\x01\n" +
	"\x14OpenBaoJobStatusSpec\x12\x1e\n" +
	"\n" +
	"configured\x18\x01 \x01(\bR\n" +
	"configured\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x15\n" +
	"\x06job_id\x18\x03 \x01(\tR\x05jobId\x12'\n" +
	"\x0fnomad_reachable\x18\x04 \x01(\bR\x0enomadReachable\x12\x18\n" +
	"\apresent\x18\x05 \x01(\bR\apresent\x12\x1d\n" +
	"\n" +
	"last_error\x18\x06 \x01(\tR\tlastError\"\x9e\x01\n" +
	"\x13OpenGyozaStatusSpec\x12\x1e\n" +
	"\n" +
	"configured\x18\x01 \x01(\bR\n" +
	"configured\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x18\n" +
	"\arunning\x18\x03 \x01(\bR\arunning\x12\x18\n" +
	"\ahealthy\x18\x04 \x01(\bR\ahealthy\x12\x1f\n" +
	"\vbinary_mode\x18\x05 \x01(\tR\n" +
	"binaryMode\"\x9f\x01\n" +
	"\x14OpenWontonStatusSpec\x12\x1e\n" +
	"\n" +
	"configured\x18\x01 \x01(\bR\n" +
	"configured\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x18\n" +
	"\arunning\x18\x03 \x01(\bR\arunning\x12\x18\n" +
	"\ahealthy\x18\x04 \x01(\bR\ahealthy\x12\x1f\n" +
	"\vbinary_mode\x18\x05 \x01(\tR\n" +
	"binaryModeBs\n" +
	"(dev.chubo.api.resource.definitions.chuboZGgithub.com/chubo-dev/chubo/pkg/machinery/api/resource/definitions/chubob\x06proto3"

var (
	file_resource_definitions_chubo_chubo_proto_rawDescOnce sync.Once
	file_resource_definitions_chubo_chubo_proto_rawDescData []byte
)

func file_resource_definitions_chubo_chubo_proto_rawDescGZIP() []byte {
	file_resource_definitions_chubo_chubo_proto_rawDescOnce.Do(func() {
		file_resource_definitions_chubo_chubo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_definitions_chubo_chubo_proto_rawDesc), len(file_resource_definitions_chubo_chubo_proto_rawDesc)))
	})
	return file_resource_definitions_chubo_chubo_proto_rawDescData
}

var file_resource_definitions_chubo_chubo_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_resource_definitions_chubo_chubo_proto_goTypes = []any{
	(*BootstrapStatusSpec)(nil),  // 0: talos.resource.definitions.chubo.BootstrapStatusSpec
	(*OpenBaoJobStatusSpec)(nil), // 1: talos.resource.definitions.chubo.OpenBaoJobStatusSpec
	(*OpenGyozaStatusSpec)(nil),  // 2: talos.resource.definitions.chubo.OpenGyozaStatusSpec
	(*OpenWontonStatusSpec)(nil), // 3: talos.resource.definitions.chubo.OpenWontonStatusSpec
}
var file_resource_definitions_chubo_chubo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_resource_definitions_chubo_chubo_proto_init() }
func file_resource_definitions_chubo_chubo_proto_init() {
	if File_resource_definitions_chubo_chubo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_definitions_chubo_chubo_proto_rawDesc), len(file_resource_definitions_chubo_chubo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resource_definitions_chubo_chubo_proto_goTypes,
		DependencyIndexes: file_resource_definitions_chubo_chubo_proto_depIdxs,
		MessageInfos:      file_resource_definitions_chubo_chubo_proto_msgTypes,
	}.Build()
	File_resource_definitions_chubo_chubo_proto = out.File
	file_resource_definitions_chubo_chubo_proto_goTypes = nil
	file_resource_definitions_chubo_chubo_proto_depIdxs = nil
}
