#!/usr/bin/env bash
set -euo pipefail

# Verifies that chubo build targets don't introduce new disallowed Go package deps.
#
# Policy:
# - forbidden prefixes: k[0-9]s.io/* and go.etc[d].io/etc[d]/*
# - cmd/talosctl is strict: zero forbidden deps allowed
# - baseline file stores currently-allowed package paths for incremental targets
# - check fails when:
#   * cmd/talosctl has any forbidden deps
#   * current deps include package paths not present in baseline
# - removals are reported as improvement (baseline can be tightened with --update)
#
# Usage:
#   hack/chubo/check-go-deps.sh
#   hack/chubo/check-go-deps.sh --update
#   hack/chubo/check-go-deps.sh --baseline path/to/file

BASELINE="hack/chubo/forbidden-go-deps-baseline.txt"
UPDATE=0

while [[ $# -gt 0 ]]; do
	case "$1" in
	--baseline)
		BASELINE="$2"
		shift 2
		;;
	--update)
		UPDATE=1
		shift
		;;
	-h | --help)
		sed -n '1,40p' "$0"
		exit 0
		;;
	*)
		echo "unknown argument: $1" >&2
		exit 2
		;;
	esac
done

if [[ "${BASELINE}" != /* ]]; then
	BASELINE="$(pwd)/${BASELINE}"
fi

if ! command -v go >/dev/null 2>&1; then
	echo "missing required command: go" >&2
	exit 2
fi

# Keep target matrix explicit so regressions are obvious.
TARGETS=(
	"linux arm64 0 internal/app/machined"
	"linux amd64 0 cmd/talosctl"
)

TAGS="tcell_minimal,grpcnotrace,chubo"
forbidden_dep_re='^(k[0-9]s\.io/|go\.etc[d]\.io/etc[d])'
workdir="$(mktemp -d /tmp/chubo-go-deps-check.XXXXXX)"
trap 'rm -rf "${workdir}"' EXIT
current_file="${workdir}/current.txt"
current_raw="${workdir}/current-raw.txt"
strict_cmd_talosctl_file="${workdir}/cmd_talosctl_forbidden.txt"

: >"${current_raw}"
: >"${strict_cmd_talosctl_file}"

for target_spec in "${TARGETS[@]}"; do
	read -r goos goarch cgo target <<<"${target_spec}"
	echo "Collecting deps for ${target} (GOOS=${goos} GOARCH=${goarch} CGO_ENABLED=${cgo})"
	target_raw="${workdir}/${target//\//_}.raw.txt"
	target_forbidden="${workdir}/${target//\//_}.forbidden.txt"

	GOOS="${goos}" GOARCH="${goarch}" CGO_ENABLED="${cgo}" \
		go list -deps -tags "${TAGS}" "./${target}" >"${target_raw}"

	cat "${target_raw}" >>"${current_raw}"

	sort -u "${target_raw}" | grep -E "${forbidden_dep_re}" >"${target_forbidden}" || true

	target_count="$(wc -l <"${target_forbidden}" | tr -d ' ')"
	echo "  forbidden deps for ${target}: ${target_count}"

	if [[ "${target}" == "cmd/talosctl" ]]; then
		cat "${target_forbidden}" >"${strict_cmd_talosctl_file}"
	fi
done

sort -u "${current_raw}" | grep -E "${forbidden_dep_re}" >"${current_file}" || true

if [[ -s "${strict_cmd_talosctl_file}" ]]; then
	echo "FAIL: cmd/talosctl must not import forbidden package deps:" >&2
	sed 's/^/  + /' "${strict_cmd_talosctl_file}" >&2
	exit 1
fi

if [[ "${UPDATE}" -eq 1 ]]; then
	mkdir -p "$(dirname "${BASELINE}")"
	{
		echo "# Chubo forbidden-deps baseline"
		echo "#"
		echo "# Generated by: hack/chubo/check-go-deps.sh --update"
		echo "# Forbidden prefixes: k[0-9]s.io/*, go.etc[d].io/etc[d]/*"
		echo "# This baseline is an upper bound: CI fails on newly added paths."
		echo "# Last updated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
		echo "#"
		cat "${current_file}"
	} >"${BASELINE}"
	echo "Updated baseline: ${BASELINE}"
	exit 0
fi

if [[ ! -f "${BASELINE}" ]]; then
	echo "baseline file not found: ${BASELINE}" >&2
	echo "run: $0 --update" >&2
	exit 2
fi

baseline_file="${workdir}/baseline.txt"
grep -E "${forbidden_dep_re}" "${BASELINE}" | sort -u >"${baseline_file}" || true

added_file="${workdir}/added.txt"
removed_file="${workdir}/removed.txt"

comm -13 "${baseline_file}" "${current_file}" >"${added_file}" || true
comm -23 "${baseline_file}" "${current_file}" >"${removed_file}" || true

if [[ -s "${added_file}" ]]; then
	echo "FAIL: new forbidden package deps introduced:" >&2
	sed 's/^/  + /' "${added_file}" >&2
	echo >&2
	echo "If this is intentional, update baseline with:" >&2
	echo "  hack/chubo/check-go-deps.sh --update" >&2
	exit 1
fi

echo "OK: no new forbidden package deps introduced"

if [[ -s "${removed_file}" ]]; then
	echo "NOTE: forbidden deps removed; baseline can be tightened:" >&2
	sed 's/^/  - /' "${removed_file}" >&2
	echo "Run: hack/chubo/check-go-deps.sh --update" >&2
fi

current_count="$(wc -l <"${current_file}" | tr -d ' ')"
echo "Current forbidden package count: ${current_count}"
