// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: resource/definitions/secrets/secrets.proto

package secrets

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"

	common "github.com/chubo-dev/chubo/pkg/machinery/api/common"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// APICertsSpec describes etcd certs secrets.
type APICertsSpec struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Client        *common.PEMEncodedCertificateAndKey `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	Server        *common.PEMEncodedCertificateAndKey `protobuf:"bytes,3,opt,name=server,proto3" json:"server,omitempty"`
	AcceptedCAs   []*common.PEMEncodedCertificate     `protobuf:"bytes,4,rep,name=accepted_c_as,json=acceptedCAs,proto3" json:"accepted_c_as,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APICertsSpec) Reset() {
	*x = APICertsSpec{}
	mi := &file_resource_definitions_secrets_secrets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APICertsSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APICertsSpec) ProtoMessage() {}

func (x *APICertsSpec) ProtoReflect() protoreflect.Message {
	mi := &file_resource_definitions_secrets_secrets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APICertsSpec.ProtoReflect.Descriptor instead.
func (*APICertsSpec) Descriptor() ([]byte, []int) {
	return file_resource_definitions_secrets_secrets_proto_rawDescGZIP(), []int{0}
}

func (x *APICertsSpec) GetClient() *common.PEMEncodedCertificateAndKey {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *APICertsSpec) GetServer() *common.PEMEncodedCertificateAndKey {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *APICertsSpec) GetAcceptedCAs() []*common.PEMEncodedCertificate {
	if x != nil {
		return x.AcceptedCAs
	}
	return nil
}

// CertSANSpec describes fields of the cert SANs.
type CertSANSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IPs           []*common.NetIP        `protobuf:"bytes,1,rep,name=i_ps,json=iPs,proto3" json:"i_ps,omitempty"`
	DnsNames      []string               `protobuf:"bytes,2,rep,name=dns_names,json=dnsNames,proto3" json:"dns_names,omitempty"`
	Fqdn          string                 `protobuf:"bytes,3,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertSANSpec) Reset() {
	*x = CertSANSpec{}
	mi := &file_resource_definitions_secrets_secrets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertSANSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertSANSpec) ProtoMessage() {}

func (x *CertSANSpec) ProtoReflect() protoreflect.Message {
	mi := &file_resource_definitions_secrets_secrets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertSANSpec.ProtoReflect.Descriptor instead.
func (*CertSANSpec) Descriptor() ([]byte, []int) {
	return file_resource_definitions_secrets_secrets_proto_rawDescGZIP(), []int{1}
}

func (x *CertSANSpec) GetIPs() []*common.NetIP {
	if x != nil {
		return x.IPs
	}
	return nil
}

func (x *CertSANSpec) GetDnsNames() []string {
	if x != nil {
		return x.DnsNames
	}
	return nil
}

func (x *CertSANSpec) GetFqdn() string {
	if x != nil {
		return x.Fqdn
	}
	return ""
}

// EncryptionSaltSpec describes the salt.
type EncryptionSaltSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiskSalt      []byte                 `protobuf:"bytes,1,opt,name=disk_salt,json=diskSalt,proto3" json:"disk_salt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptionSaltSpec) Reset() {
	*x = EncryptionSaltSpec{}
	mi := &file_resource_definitions_secrets_secrets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptionSaltSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptionSaltSpec) ProtoMessage() {}

func (x *EncryptionSaltSpec) ProtoReflect() protoreflect.Message {
	mi := &file_resource_definitions_secrets_secrets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptionSaltSpec.ProtoReflect.Descriptor instead.
func (*EncryptionSaltSpec) Descriptor() ([]byte, []int) {
	return file_resource_definitions_secrets_secrets_proto_rawDescGZIP(), []int{2}
}

func (x *EncryptionSaltSpec) GetDiskSalt() []byte {
	if x != nil {
		return x.DiskSalt
	}
	return nil
}

// EtcdCertsSpec describes etcd certs secrets.
type EtcdCertsSpec struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Etcd          *common.PEMEncodedCertificateAndKey `protobuf:"bytes,1,opt,name=etcd,proto3" json:"etcd,omitempty"`
	EtcdPeer      *common.PEMEncodedCertificateAndKey `protobuf:"bytes,2,opt,name=etcd_peer,json=etcdPeer,proto3" json:"etcd_peer,omitempty"`
	EtcdAdmin     *common.PEMEncodedCertificateAndKey `protobuf:"bytes,3,opt,name=etcd_admin,json=etcdAdmin,proto3" json:"etcd_admin,omitempty"`
	EtcdApiServer *common.PEMEncodedCertificateAndKey `protobuf:"bytes,4,opt,name=etcd_api_server,json=etcdApiServer,proto3" json:"etcd_api_server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EtcdCertsSpec) Reset() {
	*x = EtcdCertsSpec{}
	mi := &file_resource_definitions_secrets_secrets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EtcdCertsSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EtcdCertsSpec) ProtoMessage() {}

func (x *EtcdCertsSpec) ProtoReflect() protoreflect.Message {
	mi := &file_resource_definitions_secrets_secrets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EtcdCertsSpec.ProtoReflect.Descriptor instead.
func (*EtcdCertsSpec) Descriptor() ([]byte, []int) {
	return file_resource_definitions_secrets_secrets_proto_rawDescGZIP(), []int{3}
}

func (x *EtcdCertsSpec) GetEtcd() *common.PEMEncodedCertificateAndKey {
	if x != nil {
		return x.Etcd
	}
	return nil
}

func (x *EtcdCertsSpec) GetEtcdPeer() *common.PEMEncodedCertificateAndKey {
	if x != nil {
		return x.EtcdPeer
	}
	return nil
}

func (x *EtcdCertsSpec) GetEtcdAdmin() *common.PEMEncodedCertificateAndKey {
	if x != nil {
		return x.EtcdAdmin
	}
	return nil
}

func (x *EtcdCertsSpec) GetEtcdApiServer() *common.PEMEncodedCertificateAndKey {
	if x != nil {
		return x.EtcdApiServer
	}
	return nil
}

// EtcdRootSpec describes etcd CA secrets.
type EtcdRootSpec struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	EtcdCa        *common.PEMEncodedCertificateAndKey `protobuf:"bytes,1,opt,name=etcd_ca,json=etcdCa,proto3" json:"etcd_ca,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EtcdRootSpec) Reset() {
	*x = EtcdRootSpec{}
	mi := &file_resource_definitions_secrets_secrets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EtcdRootSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EtcdRootSpec) ProtoMessage() {}

func (x *EtcdRootSpec) ProtoReflect() protoreflect.Message {
	mi := &file_resource_definitions_secrets_secrets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EtcdRootSpec.ProtoReflect.Descriptor instead.
func (*EtcdRootSpec) Descriptor() ([]byte, []int) {
	return file_resource_definitions_secrets_secrets_proto_rawDescGZIP(), []int{4}
}

func (x *EtcdRootSpec) GetEtcdCa() *common.PEMEncodedCertificateAndKey {
	if x != nil {
		return x.EtcdCa
	}
	return nil
}

// MaintenanceRootSpec describes maintenance service CA.
type MaintenanceRootSpec struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Ca            *common.PEMEncodedCertificateAndKey `protobuf:"bytes,1,opt,name=ca,proto3" json:"ca,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaintenanceRootSpec) Reset() {
	*x = MaintenanceRootSpec{}
	mi := &file_resource_definitions_secrets_secrets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaintenanceRootSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintenanceRootSpec) ProtoMessage() {}

func (x *MaintenanceRootSpec) ProtoReflect() protoreflect.Message {
	mi := &file_resource_definitions_secrets_secrets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaintenanceRootSpec.ProtoReflect.Descriptor instead.
func (*MaintenanceRootSpec) Descriptor() ([]byte, []int) {
	return file_resource_definitions_secrets_secrets_proto_rawDescGZIP(), []int{5}
}

func (x *MaintenanceRootSpec) GetCa() *common.PEMEncodedCertificateAndKey {
	if x != nil {
		return x.Ca
	}
	return nil
}

// MaintenanceServiceCertsSpec describes maintenance service certs secrets.
type MaintenanceServiceCertsSpec struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Ca            *common.PEMEncodedCertificateAndKey `protobuf:"bytes,1,opt,name=ca,proto3" json:"ca,omitempty"`
	Server        *common.PEMEncodedCertificateAndKey `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaintenanceServiceCertsSpec) Reset() {
	*x = MaintenanceServiceCertsSpec{}
	mi := &file_resource_definitions_secrets_secrets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaintenanceServiceCertsSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintenanceServiceCertsSpec) ProtoMessage() {}

func (x *MaintenanceServiceCertsSpec) ProtoReflect() protoreflect.Message {
	mi := &file_resource_definitions_secrets_secrets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaintenanceServiceCertsSpec.ProtoReflect.Descriptor instead.
func (*MaintenanceServiceCertsSpec) Descriptor() ([]byte, []int) {
	return file_resource_definitions_secrets_secrets_proto_rawDescGZIP(), []int{6}
}

func (x *MaintenanceServiceCertsSpec) GetCa() *common.PEMEncodedCertificateAndKey {
	if x != nil {
		return x.Ca
	}
	return nil
}

func (x *MaintenanceServiceCertsSpec) GetServer() *common.PEMEncodedCertificateAndKey {
	if x != nil {
		return x.Server
	}
	return nil
}

// OSRootSpec describes operating system CA.
type OSRootSpec struct {
	state           protoimpl.MessageState              `protogen:"open.v1"`
	IssuingCa       *common.PEMEncodedCertificateAndKey `protobuf:"bytes,1,opt,name=issuing_ca,json=issuingCa,proto3" json:"issuing_ca,omitempty"`
	CertSaniPs      []*common.NetIP                     `protobuf:"bytes,2,rep,name=cert_sani_ps,json=certSaniPs,proto3" json:"cert_sani_ps,omitempty"`
	CertSandnsNames []string                            `protobuf:"bytes,3,rep,name=cert_sandns_names,json=certSandnsNames,proto3" json:"cert_sandns_names,omitempty"`
	Token           string                              `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	AcceptedCAs     []*common.PEMEncodedCertificate     `protobuf:"bytes,5,rep,name=accepted_c_as,json=acceptedCAs,proto3" json:"accepted_c_as,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OSRootSpec) Reset() {
	*x = OSRootSpec{}
	mi := &file_resource_definitions_secrets_secrets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OSRootSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSRootSpec) ProtoMessage() {}

func (x *OSRootSpec) ProtoReflect() protoreflect.Message {
	mi := &file_resource_definitions_secrets_secrets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSRootSpec.ProtoReflect.Descriptor instead.
func (*OSRootSpec) Descriptor() ([]byte, []int) {
	return file_resource_definitions_secrets_secrets_proto_rawDescGZIP(), []int{7}
}

func (x *OSRootSpec) GetIssuingCa() *common.PEMEncodedCertificateAndKey {
	if x != nil {
		return x.IssuingCa
	}
	return nil
}

func (x *OSRootSpec) GetCertSaniPs() []*common.NetIP {
	if x != nil {
		return x.CertSaniPs
	}
	return nil
}

func (x *OSRootSpec) GetCertSandnsNames() []string {
	if x != nil {
		return x.CertSandnsNames
	}
	return nil
}

func (x *OSRootSpec) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *OSRootSpec) GetAcceptedCAs() []*common.PEMEncodedCertificate {
	if x != nil {
		return x.AcceptedCAs
	}
	return nil
}

// TrustdCertsSpec describes etcd certs secrets.
type TrustdCertsSpec struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Server        *common.PEMEncodedCertificateAndKey `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	AcceptedCAs   []*common.PEMEncodedCertificate     `protobuf:"bytes,3,rep,name=accepted_c_as,json=acceptedCAs,proto3" json:"accepted_c_as,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrustdCertsSpec) Reset() {
	*x = TrustdCertsSpec{}
	mi := &file_resource_definitions_secrets_secrets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustdCertsSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustdCertsSpec) ProtoMessage() {}

func (x *TrustdCertsSpec) ProtoReflect() protoreflect.Message {
	mi := &file_resource_definitions_secrets_secrets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustdCertsSpec.ProtoReflect.Descriptor instead.
func (*TrustdCertsSpec) Descriptor() ([]byte, []int) {
	return file_resource_definitions_secrets_secrets_proto_rawDescGZIP(), []int{8}
}

func (x *TrustdCertsSpec) GetServer() *common.PEMEncodedCertificateAndKey {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *TrustdCertsSpec) GetAcceptedCAs() []*common.PEMEncodedCertificate {
	if x != nil {
		return x.AcceptedCAs
	}
	return nil
}

var File_resource_definitions_secrets_secrets_proto protoreflect.FileDescriptor

const file_resource_definitions_secrets_secrets_proto_rawDesc = "" +
	"\n" +
	"*resource/definitions/secrets/secrets.proto\x12\"talos.resource.definitions.secrets\x1a\x13common/common.proto\"\xcb\x01\n" +
	"\fAPICertsSpec\x12;\n" +
	"\x06client\x18\x02 \x01(\v2#.common.PEMEncodedCertificateAndKeyR\x06client\x12;\n" +
	"\x06server\x18\x03 \x01(\v2#.common.PEMEncodedCertificateAndKeyR\x06server\x12A\n" +
	"\raccepted_c_as\x18\x04 \x03(\v2\x1d.common.PEMEncodedCertificateR\vacceptedCAs\"`\n" +
	"\vCertSANSpec\x12 \n" +
	"\x04i_ps\x18\x01 \x03(\v2\r.common.NetIPR\x03iPs\x12\x1b\n" +
	"\tdns_names\x18\x02 \x03(\tR\bdnsNames\x12\x12\n" +
	"\x04fqdn\x18\x03 \x01(\tR\x04fqdn\"1\n" +
	"\x12EncryptionSaltSpec\x12\x1b\n" +
	"\tdisk_salt\x18\x01 \x01(\fR\bdiskSalt\"\x9b\x02\n" +
	"\rEtcdCertsSpec\x127\n" +
	"\x04etcd\x18\x01 \x01(\v2#.common.PEMEncodedCertificateAndKeyR\x04etcd\x12@\n" +
	"\tetcd_peer\x18\x02 \x01(\v2#.common.PEMEncodedCertificateAndKeyR\betcdPeer\x12B\n" +
	"\n" +
	"etcd_admin\x18\x03 \x01(\v2#.common.PEMEncodedCertificateAndKeyR\tetcdAdmin\x12K\n" +
	"\x0fetcd_api_server\x18\x04 \x01(\v2#.common.PEMEncodedCertificateAndKeyR\retcdApiServer\"L\n" +
	"\fEtcdRootSpec\x12<\n" +
	"\aetcd_ca\x18\x01 \x01(\v2#.common.PEMEncodedCertificateAndKeyR\x06etcdCa\"J\n" +
	"\x13MaintenanceRootSpec\x123\n" +
	"\x02ca\x18\x01 \x01(\v2#.common.PEMEncodedCertificateAndKeyR\x02ca\"\x8f\x01\n" +
	"\x1bMaintenanceServiceCertsSpec\x123\n" +
	"\x02ca\x18\x01 \x01(\v2#.common.PEMEncodedCertificateAndKeyR\x02ca\x12;\n" +
	"\x06server\x18\x02 \x01(\v2#.common.PEMEncodedCertificateAndKeyR\x06server\"\x86\x02\n" +
	"\n" +
	"OSRootSpec\x12B\n" +
	"\n" +
	"issuing_ca\x18\x01 \x01(\v2#.common.PEMEncodedCertificateAndKeyR\tissuingCa\x12/\n" +
	"\fcert_sani_ps\x18\x02 \x03(\v2\r.common.NetIPR\n" +
	"certSaniPs\x12*\n" +
	"\x11cert_sandns_names\x18\x03 \x03(\tR\x0fcertSandnsNames\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x12A\n" +
	"\raccepted_c_as\x18\x05 \x03(\v2\x1d.common.PEMEncodedCertificateR\vacceptedCAs\"\x91\x01\n" +
	"\x0fTrustdCertsSpec\x12;\n" +
	"\x06server\x18\x02 \x01(\v2#.common.PEMEncodedCertificateAndKeyR\x06server\x12A\n" +
	"\raccepted_c_as\x18\x03 \x03(\v2\x1d.common.PEMEncodedCertificateR\vacceptedCAsBw\n" +
	"*dev.chubo.api.resource.definitions.secretsZIgithub.com/chubo-dev/chubo/pkg/machinery/api/resource/definitions/secretsb\x06proto3"

var (
	file_resource_definitions_secrets_secrets_proto_rawDescOnce sync.Once
	file_resource_definitions_secrets_secrets_proto_rawDescData []byte
)

func file_resource_definitions_secrets_secrets_proto_rawDescGZIP() []byte {
	file_resource_definitions_secrets_secrets_proto_rawDescOnce.Do(func() {
		file_resource_definitions_secrets_secrets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_definitions_secrets_secrets_proto_rawDesc), len(file_resource_definitions_secrets_secrets_proto_rawDesc)))
	})
	return file_resource_definitions_secrets_secrets_proto_rawDescData
}

var file_resource_definitions_secrets_secrets_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_resource_definitions_secrets_secrets_proto_goTypes = []any{
	(*APICertsSpec)(nil),                       // 0: talos.resource.definitions.secrets.APICertsSpec
	(*CertSANSpec)(nil),                        // 1: talos.resource.definitions.secrets.CertSANSpec
	(*EncryptionSaltSpec)(nil),                 // 2: talos.resource.definitions.secrets.EncryptionSaltSpec
	(*EtcdCertsSpec)(nil),                      // 3: talos.resource.definitions.secrets.EtcdCertsSpec
	(*EtcdRootSpec)(nil),                       // 4: talos.resource.definitions.secrets.EtcdRootSpec
	(*MaintenanceRootSpec)(nil),                // 5: talos.resource.definitions.secrets.MaintenanceRootSpec
	(*MaintenanceServiceCertsSpec)(nil),        // 6: talos.resource.definitions.secrets.MaintenanceServiceCertsSpec
	(*OSRootSpec)(nil),                         // 7: talos.resource.definitions.secrets.OSRootSpec
	(*TrustdCertsSpec)(nil),                    // 8: talos.resource.definitions.secrets.TrustdCertsSpec
	(*common.PEMEncodedCertificateAndKey)(nil), // 9: common.PEMEncodedCertificateAndKey
	(*common.PEMEncodedCertificate)(nil),       // 10: common.PEMEncodedCertificate
	(*common.NetIP)(nil),                       // 11: common.NetIP
}
var file_resource_definitions_secrets_secrets_proto_depIdxs = []int32{
	9,  // 0: talos.resource.definitions.secrets.APICertsSpec.client:type_name -> common.PEMEncodedCertificateAndKey
	9,  // 1: talos.resource.definitions.secrets.APICertsSpec.server:type_name -> common.PEMEncodedCertificateAndKey
	10, // 2: talos.resource.definitions.secrets.APICertsSpec.accepted_c_as:type_name -> common.PEMEncodedCertificate
	11, // 3: talos.resource.definitions.secrets.CertSANSpec.i_ps:type_name -> common.NetIP
	9,  // 4: talos.resource.definitions.secrets.EtcdCertsSpec.etcd:type_name -> common.PEMEncodedCertificateAndKey
	9,  // 5: talos.resource.definitions.secrets.EtcdCertsSpec.etcd_peer:type_name -> common.PEMEncodedCertificateAndKey
	9,  // 6: talos.resource.definitions.secrets.EtcdCertsSpec.etcd_admin:type_name -> common.PEMEncodedCertificateAndKey
	9,  // 7: talos.resource.definitions.secrets.EtcdCertsSpec.etcd_api_server:type_name -> common.PEMEncodedCertificateAndKey
	9,  // 8: talos.resource.definitions.secrets.EtcdRootSpec.etcd_ca:type_name -> common.PEMEncodedCertificateAndKey
	9,  // 9: talos.resource.definitions.secrets.MaintenanceRootSpec.ca:type_name -> common.PEMEncodedCertificateAndKey
	9,  // 10: talos.resource.definitions.secrets.MaintenanceServiceCertsSpec.ca:type_name -> common.PEMEncodedCertificateAndKey
	9,  // 11: talos.resource.definitions.secrets.MaintenanceServiceCertsSpec.server:type_name -> common.PEMEncodedCertificateAndKey
	9,  // 12: talos.resource.definitions.secrets.OSRootSpec.issuing_ca:type_name -> common.PEMEncodedCertificateAndKey
	11, // 13: talos.resource.definitions.secrets.OSRootSpec.cert_sani_ps:type_name -> common.NetIP
	10, // 14: talos.resource.definitions.secrets.OSRootSpec.accepted_c_as:type_name -> common.PEMEncodedCertificate
	9,  // 15: talos.resource.definitions.secrets.TrustdCertsSpec.server:type_name -> common.PEMEncodedCertificateAndKey
	10, // 16: talos.resource.definitions.secrets.TrustdCertsSpec.accepted_c_as:type_name -> common.PEMEncodedCertificate
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_resource_definitions_secrets_secrets_proto_init() }
func file_resource_definitions_secrets_secrets_proto_init() {
	if File_resource_definitions_secrets_secrets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_definitions_secrets_secrets_proto_rawDesc), len(file_resource_definitions_secrets_secrets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resource_definitions_secrets_secrets_proto_goTypes,
		DependencyIndexes: file_resource_definitions_secrets_secrets_proto_depIdxs,
		MessageInfos:      file_resource_definitions_secrets_secrets_proto_msgTypes,
	}.Build()
	File_resource_definitions_secrets_secrets_proto = out.File
	file_resource_definitions_secrets_secrets_proto_goTypes = nil
	file_resource_definitions_secrets_secrets_proto_depIdxs = nil
}
