// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: resource/definitions/cluster/cluster.proto

package cluster

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"

	common "github.com/chubo-dev/chubo/pkg/machinery/api/common"
	enums "github.com/chubo-dev/chubo/pkg/machinery/api/resource/definitions/enums"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AffiliateSpec describes Affiliate state.
type AffiliateSpec struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Addresses       []*common.NetIP        `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Hostname        string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Nodename        string                 `protobuf:"bytes,4,opt,name=nodename,proto3" json:"nodename,omitempty"`
	OperatingSystem string                 `protobuf:"bytes,5,opt,name=operating_system,json=operatingSystem,proto3" json:"operating_system,omitempty"`
	MachineType     enums.MachineType      `protobuf:"varint,6,opt,name=machine_type,json=machineType,proto3,enum=chubo.resource.definitions.enums.MachineType" json:"machine_type,omitempty"`
	ControlPlane    *ControlPlane          `protobuf:"bytes,8,opt,name=control_plane,json=controlPlane,proto3" json:"control_plane,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AffiliateSpec) Reset() {
	*x = AffiliateSpec{}
	mi := &file_resource_definitions_cluster_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AffiliateSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AffiliateSpec) ProtoMessage() {}

func (x *AffiliateSpec) ProtoReflect() protoreflect.Message {
	mi := &file_resource_definitions_cluster_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AffiliateSpec.ProtoReflect.Descriptor instead.
func (*AffiliateSpec) Descriptor() ([]byte, []int) {
	return file_resource_definitions_cluster_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *AffiliateSpec) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AffiliateSpec) GetAddresses() []*common.NetIP {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *AffiliateSpec) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AffiliateSpec) GetNodename() string {
	if x != nil {
		return x.Nodename
	}
	return ""
}

func (x *AffiliateSpec) GetOperatingSystem() string {
	if x != nil {
		return x.OperatingSystem
	}
	return ""
}

func (x *AffiliateSpec) GetMachineType() enums.MachineType {
	if x != nil {
		return x.MachineType
	}
	return enums.MachineType(0)
}

func (x *AffiliateSpec) GetControlPlane() *ControlPlane {
	if x != nil {
		return x.ControlPlane
	}
	return nil
}

// ConfigSpec describes cluster discovery configuration.
type ConfigSpec struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	DiscoveryEnabled        bool                   `protobuf:"varint,1,opt,name=discovery_enabled,json=discoveryEnabled,proto3" json:"discovery_enabled,omitempty"`
	RegistryServiceEnabled  bool                   `protobuf:"varint,3,opt,name=registry_service_enabled,json=registryServiceEnabled,proto3" json:"registry_service_enabled,omitempty"`
	ServiceEndpoint         string                 `protobuf:"bytes,4,opt,name=service_endpoint,json=serviceEndpoint,proto3" json:"service_endpoint,omitempty"`
	ServiceEndpointInsecure bool                   `protobuf:"varint,5,opt,name=service_endpoint_insecure,json=serviceEndpointInsecure,proto3" json:"service_endpoint_insecure,omitempty"`
	ServiceEncryptionKey    []byte                 `protobuf:"bytes,6,opt,name=service_encryption_key,json=serviceEncryptionKey,proto3" json:"service_encryption_key,omitempty"`
	ServiceClusterId        string                 `protobuf:"bytes,7,opt,name=service_cluster_id,json=serviceClusterId,proto3" json:"service_cluster_id,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ConfigSpec) Reset() {
	*x = ConfigSpec{}
	mi := &file_resource_definitions_cluster_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSpec) ProtoMessage() {}

func (x *ConfigSpec) ProtoReflect() protoreflect.Message {
	mi := &file_resource_definitions_cluster_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSpec.ProtoReflect.Descriptor instead.
func (*ConfigSpec) Descriptor() ([]byte, []int) {
	return file_resource_definitions_cluster_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigSpec) GetDiscoveryEnabled() bool {
	if x != nil {
		return x.DiscoveryEnabled
	}
	return false
}

func (x *ConfigSpec) GetRegistryServiceEnabled() bool {
	if x != nil {
		return x.RegistryServiceEnabled
	}
	return false
}

func (x *ConfigSpec) GetServiceEndpoint() string {
	if x != nil {
		return x.ServiceEndpoint
	}
	return ""
}

func (x *ConfigSpec) GetServiceEndpointInsecure() bool {
	if x != nil {
		return x.ServiceEndpointInsecure
	}
	return false
}

func (x *ConfigSpec) GetServiceEncryptionKey() []byte {
	if x != nil {
		return x.ServiceEncryptionKey
	}
	return nil
}

func (x *ConfigSpec) GetServiceClusterId() string {
	if x != nil {
		return x.ServiceClusterId
	}
	return ""
}

// ControlPlane describes ControlPlane data if any.
type ControlPlane struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiServerPort int64                  `protobuf:"varint,1,opt,name=api_server_port,json=apiServerPort,proto3" json:"api_server_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlPlane) Reset() {
	*x = ControlPlane{}
	mi := &file_resource_definitions_cluster_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlPlane) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlPlane) ProtoMessage() {}

func (x *ControlPlane) ProtoReflect() protoreflect.Message {
	mi := &file_resource_definitions_cluster_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlPlane.ProtoReflect.Descriptor instead.
func (*ControlPlane) Descriptor() ([]byte, []int) {
	return file_resource_definitions_cluster_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *ControlPlane) GetApiServerPort() int64 {
	if x != nil {
		return x.ApiServerPort
	}
	return 0
}

// ControlPlaneEndpointSpec describes a list of endpoints to connect to.
type ControlPlaneEndpointSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []*common.NetIP        `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Hosts         []string               `protobuf:"bytes,2,rep,name=hosts,proto3" json:"hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlPlaneEndpointSpec) Reset() {
	*x = ControlPlaneEndpointSpec{}
	mi := &file_resource_definitions_cluster_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlPlaneEndpointSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlPlaneEndpointSpec) ProtoMessage() {}

func (x *ControlPlaneEndpointSpec) ProtoReflect() protoreflect.Message {
	mi := &file_resource_definitions_cluster_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlPlaneEndpointSpec.ProtoReflect.Descriptor instead.
func (*ControlPlaneEndpointSpec) Descriptor() ([]byte, []int) {
	return file_resource_definitions_cluster_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *ControlPlaneEndpointSpec) GetAddresses() []*common.NetIP {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *ControlPlaneEndpointSpec) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

// IdentitySpec describes status of rendered secrets.
//
// Note: IdentitySpec is persisted on disk in the STATE partition,
// so YAML serialization should be kept backwards compatible.
type IdentitySpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentitySpec) Reset() {
	*x = IdentitySpec{}
	mi := &file_resource_definitions_cluster_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentitySpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentitySpec) ProtoMessage() {}

func (x *IdentitySpec) ProtoReflect() protoreflect.Message {
	mi := &file_resource_definitions_cluster_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentitySpec.ProtoReflect.Descriptor instead.
func (*IdentitySpec) Descriptor() ([]byte, []int) {
	return file_resource_definitions_cluster_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *IdentitySpec) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// InfoSpec describes cluster information.
type InfoSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	ClusterName   string                 `protobuf:"bytes,2,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoSpec) Reset() {
	*x = InfoSpec{}
	mi := &file_resource_definitions_cluster_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoSpec) ProtoMessage() {}

func (x *InfoSpec) ProtoReflect() protoreflect.Message {
	mi := &file_resource_definitions_cluster_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoSpec.ProtoReflect.Descriptor instead.
func (*InfoSpec) Descriptor() ([]byte, []int) {
	return file_resource_definitions_cluster_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *InfoSpec) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *InfoSpec) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

// MemberSpec describes Member state.
type MemberSpec struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Addresses       []*common.NetIP        `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Hostname        string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	MachineType     enums.MachineType      `protobuf:"varint,4,opt,name=machine_type,json=machineType,proto3,enum=chubo.resource.definitions.enums.MachineType" json:"machine_type,omitempty"`
	OperatingSystem string                 `protobuf:"bytes,5,opt,name=operating_system,json=operatingSystem,proto3" json:"operating_system,omitempty"`
	ControlPlane    *ControlPlane          `protobuf:"bytes,6,opt,name=control_plane,json=controlPlane,proto3" json:"control_plane,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MemberSpec) Reset() {
	*x = MemberSpec{}
	mi := &file_resource_definitions_cluster_cluster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberSpec) ProtoMessage() {}

func (x *MemberSpec) ProtoReflect() protoreflect.Message {
	mi := &file_resource_definitions_cluster_cluster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberSpec.ProtoReflect.Descriptor instead.
func (*MemberSpec) Descriptor() ([]byte, []int) {
	return file_resource_definitions_cluster_cluster_proto_rawDescGZIP(), []int{6}
}

func (x *MemberSpec) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MemberSpec) GetAddresses() []*common.NetIP {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *MemberSpec) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *MemberSpec) GetMachineType() enums.MachineType {
	if x != nil {
		return x.MachineType
	}
	return enums.MachineType(0)
}

func (x *MemberSpec) GetOperatingSystem() string {
	if x != nil {
		return x.OperatingSystem
	}
	return ""
}

func (x *MemberSpec) GetControlPlane() *ControlPlane {
	if x != nil {
		return x.ControlPlane
	}
	return nil
}

var File_resource_definitions_cluster_cluster_proto protoreflect.FileDescriptor

const file_resource_definitions_cluster_cluster_proto_rawDesc = "" +
	"\n" +
	"*resource/definitions/cluster/cluster.proto\x12\"chubo.resource.definitions.cluster\x1a\x13common/common.proto\x1a&resource/definitions/enums/enums.proto\"\xe1\x02\n" +
	"\rAffiliateSpec\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12+\n" +
	"\taddresses\x18\x02 \x03(\v2\r.common.NetIPR\taddresses\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1a\n" +
	"\bnodename\x18\x04 \x01(\tR\bnodename\x12)\n" +
	"\x10operating_system\x18\x05 \x01(\tR\x0foperatingSystem\x12P\n" +
	"\fmachine_type\x18\x06 \x01(\x0e2-.chubo.resource.definitions.enums.MachineTypeR\vmachineType\x12U\n" +
	"\rcontrol_plane\x18\b \x01(\v20.chubo.resource.definitions.cluster.ControlPlaneR\fcontrolPlane\"\xbe\x02\n" +
	"\n" +
	"ConfigSpec\x12+\n" +
	"\x11discovery_enabled\x18\x01 \x01(\bR\x10discoveryEnabled\x128\n" +
	"\x18registry_service_enabled\x18\x03 \x01(\bR\x16registryServiceEnabled\x12)\n" +
	"\x10service_endpoint\x18\x04 \x01(\tR\x0fserviceEndpoint\x12:\n" +
	"\x19service_endpoint_insecure\x18\x05 \x01(\bR\x17serviceEndpointInsecure\x124\n" +
	"\x16service_encryption_key\x18\x06 \x01(\fR\x14serviceEncryptionKey\x12,\n" +
	"\x12service_cluster_id\x18\a \x01(\tR\x10serviceClusterId\"6\n" +
	"\fControlPlane\x12&\n" +
	"\x0fapi_server_port\x18\x01 \x01(\x03R\rapiServerPort\"]\n" +
	"\x18ControlPlaneEndpointSpec\x12+\n" +
	"\taddresses\x18\x01 \x03(\v2\r.common.NetIPR\taddresses\x12\x14\n" +
	"\x05hosts\x18\x02 \x03(\tR\x05hosts\"'\n" +
	"\fIdentitySpec\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"L\n" +
	"\bInfoSpec\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12!\n" +
	"\fcluster_name\x18\x02 \x01(\tR\vclusterName\"\xc2\x02\n" +
	"\n" +
	"MemberSpec\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12+\n" +
	"\taddresses\x18\x02 \x03(\v2\r.common.NetIPR\taddresses\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12P\n" +
	"\fmachine_type\x18\x04 \x01(\x0e2-.chubo.resource.definitions.enums.MachineTypeR\vmachineType\x12)\n" +
	"\x10operating_system\x18\x05 \x01(\tR\x0foperatingSystem\x12U\n" +
	"\rcontrol_plane\x18\x06 \x01(\v20.chubo.resource.definitions.cluster.ControlPlaneR\fcontrolPlaneBw\n" +
	"*dev.chubo.api.resource.definitions.clusterZIgithub.com/chubo-dev/chubo/pkg/machinery/api/resource/definitions/clusterb\x06proto3"

var (
	file_resource_definitions_cluster_cluster_proto_rawDescOnce sync.Once
	file_resource_definitions_cluster_cluster_proto_rawDescData []byte
)

func file_resource_definitions_cluster_cluster_proto_rawDescGZIP() []byte {
	file_resource_definitions_cluster_cluster_proto_rawDescOnce.Do(func() {
		file_resource_definitions_cluster_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_definitions_cluster_cluster_proto_rawDesc), len(file_resource_definitions_cluster_cluster_proto_rawDesc)))
	})
	return file_resource_definitions_cluster_cluster_proto_rawDescData
}

var file_resource_definitions_cluster_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_resource_definitions_cluster_cluster_proto_goTypes = []any{
	(*AffiliateSpec)(nil),            // 0: chubo.resource.definitions.cluster.AffiliateSpec
	(*ConfigSpec)(nil),               // 1: chubo.resource.definitions.cluster.ConfigSpec
	(*ControlPlane)(nil),             // 2: chubo.resource.definitions.cluster.ControlPlane
	(*ControlPlaneEndpointSpec)(nil), // 3: chubo.resource.definitions.cluster.ControlPlaneEndpointSpec
	(*IdentitySpec)(nil),             // 4: chubo.resource.definitions.cluster.IdentitySpec
	(*InfoSpec)(nil),                 // 5: chubo.resource.definitions.cluster.InfoSpec
	(*MemberSpec)(nil),               // 6: chubo.resource.definitions.cluster.MemberSpec
	(*common.NetIP)(nil),             // 7: common.NetIP
	(enums.MachineType)(0),           // 8: chubo.resource.definitions.enums.MachineType
}
var file_resource_definitions_cluster_cluster_proto_depIdxs = []int32{
	7, // 0: chubo.resource.definitions.cluster.AffiliateSpec.addresses:type_name -> common.NetIP
	8, // 1: chubo.resource.definitions.cluster.AffiliateSpec.machine_type:type_name -> chubo.resource.definitions.enums.MachineType
	2, // 2: chubo.resource.definitions.cluster.AffiliateSpec.control_plane:type_name -> chubo.resource.definitions.cluster.ControlPlane
	7, // 3: chubo.resource.definitions.cluster.ControlPlaneEndpointSpec.addresses:type_name -> common.NetIP
	7, // 4: chubo.resource.definitions.cluster.MemberSpec.addresses:type_name -> common.NetIP
	8, // 5: chubo.resource.definitions.cluster.MemberSpec.machine_type:type_name -> chubo.resource.definitions.enums.MachineType
	2, // 6: chubo.resource.definitions.cluster.MemberSpec.control_plane:type_name -> chubo.resource.definitions.cluster.ControlPlane
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_resource_definitions_cluster_cluster_proto_init() }
func file_resource_definitions_cluster_cluster_proto_init() {
	if File_resource_definitions_cluster_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_definitions_cluster_cluster_proto_rawDesc), len(file_resource_definitions_cluster_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resource_definitions_cluster_cluster_proto_goTypes,
		DependencyIndexes: file_resource_definitions_cluster_cluster_proto_depIdxs,
		MessageInfos:      file_resource_definitions_cluster_cluster_proto_msgTypes,
	}.Build()
	File_resource_definitions_cluster_cluster_proto = out.File
	file_resource_definitions_cluster_cluster_proto_goTypes = nil
	file_resource_definitions_cluster_cluster_proto_depIdxs = nil
}
