// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// Code generated by "deep-copy -type APICertsSpec -type CertSANSpec -type EncryptionSaltSpec -type MaintenanceServiceCertsSpec -type MaintenanceRootSpec -type OSRootSpec -type TrustdCertsSpec -header-file ../../../../hack/boilerplate.txt -o deep_copy.generated.go ."; DO NOT EDIT.

package secrets

import (
	"github.com/siderolabs/crypto/x509"
	"net/netip"
)

// DeepCopy generates a deep copy of APICertsSpec.
func (o APICertsSpec) DeepCopy() APICertsSpec {
	var cp APICertsSpec = o
	if o.AcceptedCAs != nil {
		cp.AcceptedCAs = make([]*x509.PEMEncodedCertificate, len(o.AcceptedCAs))
		copy(cp.AcceptedCAs, o.AcceptedCAs)
		for i2 := range o.AcceptedCAs {
			if o.AcceptedCAs[i2] != nil {
				cp.AcceptedCAs[i2] = o.AcceptedCAs[i2].DeepCopy()
			}
		}
	}
	if o.Client != nil {
		cp.Client = o.Client.DeepCopy()
	}
	if o.Server != nil {
		cp.Server = o.Server.DeepCopy()
	}
	return cp
}

// DeepCopy generates a deep copy of CertSANSpec.
func (o CertSANSpec) DeepCopy() CertSANSpec {
	var cp CertSANSpec = o
	if o.IPs != nil {
		cp.IPs = make([]netip.Addr, len(o.IPs))
		copy(cp.IPs, o.IPs)
	}
	if o.DNSNames != nil {
		cp.DNSNames = make([]string, len(o.DNSNames))
		copy(cp.DNSNames, o.DNSNames)
	}
	return cp
}

// DeepCopy generates a deep copy of EncryptionSaltSpec.
func (o EncryptionSaltSpec) DeepCopy() EncryptionSaltSpec {
	var cp EncryptionSaltSpec = o
	if o.DiskSalt != nil {
		cp.DiskSalt = make([]byte, len(o.DiskSalt))
		copy(cp.DiskSalt, o.DiskSalt)
	}
	return cp
}

// DeepCopy generates a deep copy of MaintenanceServiceCertsSpec.
func (o MaintenanceServiceCertsSpec) DeepCopy() MaintenanceServiceCertsSpec {
	var cp MaintenanceServiceCertsSpec = o
	if o.CA != nil {
		cp.CA = o.CA.DeepCopy()
	}
	if o.Server != nil {
		cp.Server = o.Server.DeepCopy()
	}
	return cp
}

// DeepCopy generates a deep copy of MaintenanceRootSpec.
func (o MaintenanceRootSpec) DeepCopy() MaintenanceRootSpec {
	var cp MaintenanceRootSpec = o
	if o.CA != nil {
		cp.CA = o.CA.DeepCopy()
	}
	return cp
}

// DeepCopy generates a deep copy of OSRootSpec.
func (o OSRootSpec) DeepCopy() OSRootSpec {
	var cp OSRootSpec = o
	if o.IssuingCA != nil {
		cp.IssuingCA = o.IssuingCA.DeepCopy()
	}
	if o.AcceptedCAs != nil {
		cp.AcceptedCAs = make([]*x509.PEMEncodedCertificate, len(o.AcceptedCAs))
		copy(cp.AcceptedCAs, o.AcceptedCAs)
		for i2 := range o.AcceptedCAs {
			if o.AcceptedCAs[i2] != nil {
				cp.AcceptedCAs[i2] = o.AcceptedCAs[i2].DeepCopy()
			}
		}
	}
	if o.CertSANIPs != nil {
		cp.CertSANIPs = make([]netip.Addr, len(o.CertSANIPs))
		copy(cp.CertSANIPs, o.CertSANIPs)
	}
	if o.CertSANDNSNames != nil {
		cp.CertSANDNSNames = make([]string, len(o.CertSANDNSNames))
		copy(cp.CertSANDNSNames, o.CertSANDNSNames)
	}
	return cp
}

// DeepCopy generates a deep copy of TrustdCertsSpec.
func (o TrustdCertsSpec) DeepCopy() TrustdCertsSpec {
	var cp TrustdCertsSpec = o
	if o.AcceptedCAs != nil {
		cp.AcceptedCAs = make([]*x509.PEMEncodedCertificate, len(o.AcceptedCAs))
		copy(cp.AcceptedCAs, o.AcceptedCAs)
		for i2 := range o.AcceptedCAs {
			if o.AcceptedCAs[i2] != nil {
				cp.AcceptedCAs[i2] = o.AcceptedCAs[i2].DeepCopy()
			}
		}
	}
	if o.Server != nil {
		cp.Server = o.Server.DeepCopy()
	}
	return cp
}
