// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// Code generated by "deep-copy -type Config -type Device -type ArgValue -pointer-receiver -header-file ../../../../../hack/boilerplate.txt -o deep_copy.generated.go ."; DO NOT EDIT.

package v1alpha1

import (
	"github.com/siderolabs/crypto/x509"
)

// DeepCopy generates a deep copy of *Config.
func (o *Config) DeepCopy() *Config {
	var cp Config = *o
	if o.ConfigDebug != nil {
		cp.ConfigDebug = new(bool)
		*cp.ConfigDebug = *o.ConfigDebug
	}
	if o.ConfigPersist != nil {
		cp.ConfigPersist = new(bool)
		*cp.ConfigPersist = *o.ConfigPersist
	}
	if o.MachineConfig != nil {
		cp.MachineConfig = new(MachineConfig)
		*cp.MachineConfig = *o.MachineConfig
		if o.MachineConfig.MachineCA != nil {
			cp.MachineConfig.MachineCA = o.MachineConfig.MachineCA.DeepCopy()
		}
		if o.MachineConfig.MachineAcceptedCAs != nil {
			cp.MachineConfig.MachineAcceptedCAs = make([]*x509.PEMEncodedCertificate, len(o.MachineConfig.MachineAcceptedCAs))
			copy(cp.MachineConfig.MachineAcceptedCAs, o.MachineConfig.MachineAcceptedCAs)
			for i4 := range o.MachineConfig.MachineAcceptedCAs {
				if o.MachineConfig.MachineAcceptedCAs[i4] != nil {
					cp.MachineConfig.MachineAcceptedCAs[i4] = o.MachineConfig.MachineAcceptedCAs[i4].DeepCopy()
				}
			}
		}
		if o.MachineConfig.MachineCertSANs != nil {
			cp.MachineConfig.MachineCertSANs = make([]string, len(o.MachineConfig.MachineCertSANs))
			copy(cp.MachineConfig.MachineCertSANs, o.MachineConfig.MachineCertSANs)
		}
		if o.MachineConfig.MachineNetwork != nil {
			cp.MachineConfig.MachineNetwork = new(NetworkConfig)
			*cp.MachineConfig.MachineNetwork = *o.MachineConfig.MachineNetwork
			if o.MachineConfig.MachineNetwork.NetworkInterfaces != nil {
				cp.MachineConfig.MachineNetwork.NetworkInterfaces = make([]*Device, len(o.MachineConfig.MachineNetwork.NetworkInterfaces))
				copy(cp.MachineConfig.MachineNetwork.NetworkInterfaces, o.MachineConfig.MachineNetwork.NetworkInterfaces)
				for i6 := range o.MachineConfig.MachineNetwork.NetworkInterfaces {
					if o.MachineConfig.MachineNetwork.NetworkInterfaces[i6] != nil {
						cp.MachineConfig.MachineNetwork.NetworkInterfaces[i6] = o.MachineConfig.MachineNetwork.NetworkInterfaces[i6].DeepCopy()
					}
				}
			}
			if o.MachineConfig.MachineNetwork.NameServers != nil {
				cp.MachineConfig.MachineNetwork.NameServers = make([]string, len(o.MachineConfig.MachineNetwork.NameServers))
				copy(cp.MachineConfig.MachineNetwork.NameServers, o.MachineConfig.MachineNetwork.NameServers)
			}
			if o.MachineConfig.MachineNetwork.Searches != nil {
				cp.MachineConfig.MachineNetwork.Searches = make([]string, len(o.MachineConfig.MachineNetwork.Searches))
				copy(cp.MachineConfig.MachineNetwork.Searches, o.MachineConfig.MachineNetwork.Searches)
			}
			if o.MachineConfig.MachineNetwork.ExtraHostEntries != nil {
				cp.MachineConfig.MachineNetwork.ExtraHostEntries = make([]*ExtraHost, len(o.MachineConfig.MachineNetwork.ExtraHostEntries))
				copy(cp.MachineConfig.MachineNetwork.ExtraHostEntries, o.MachineConfig.MachineNetwork.ExtraHostEntries)
				for i6 := range o.MachineConfig.MachineNetwork.ExtraHostEntries {
					if o.MachineConfig.MachineNetwork.ExtraHostEntries[i6] != nil {
						cp.MachineConfig.MachineNetwork.ExtraHostEntries[i6] = new(ExtraHost)
						*cp.MachineConfig.MachineNetwork.ExtraHostEntries[i6] = *o.MachineConfig.MachineNetwork.ExtraHostEntries[i6]
						if o.MachineConfig.MachineNetwork.ExtraHostEntries[i6].HostAliases != nil {
							cp.MachineConfig.MachineNetwork.ExtraHostEntries[i6].HostAliases = make([]string, len(o.MachineConfig.MachineNetwork.ExtraHostEntries[i6].HostAliases))
							copy(cp.MachineConfig.MachineNetwork.ExtraHostEntries[i6].HostAliases, o.MachineConfig.MachineNetwork.ExtraHostEntries[i6].HostAliases)
						}
					}
				}
			}
			if o.MachineConfig.MachineNetwork.NetworkDisableSearchDomain != nil {
				cp.MachineConfig.MachineNetwork.NetworkDisableSearchDomain = new(bool)
				*cp.MachineConfig.MachineNetwork.NetworkDisableSearchDomain = *o.MachineConfig.MachineNetwork.NetworkDisableSearchDomain
			}
		}
		if o.MachineConfig.MachineDisks != nil {
			cp.MachineConfig.MachineDisks = make([]*MachineDisk, len(o.MachineConfig.MachineDisks))
			copy(cp.MachineConfig.MachineDisks, o.MachineConfig.MachineDisks)
			for i4 := range o.MachineConfig.MachineDisks {
				if o.MachineConfig.MachineDisks[i4] != nil {
					cp.MachineConfig.MachineDisks[i4] = new(MachineDisk)
					*cp.MachineConfig.MachineDisks[i4] = *o.MachineConfig.MachineDisks[i4]
					if o.MachineConfig.MachineDisks[i4].DiskPartitions != nil {
						cp.MachineConfig.MachineDisks[i4].DiskPartitions = make([]*DiskPartition, len(o.MachineConfig.MachineDisks[i4].DiskPartitions))
						copy(cp.MachineConfig.MachineDisks[i4].DiskPartitions, o.MachineConfig.MachineDisks[i4].DiskPartitions)
						for i7 := range o.MachineConfig.MachineDisks[i4].DiskPartitions {
							if o.MachineConfig.MachineDisks[i4].DiskPartitions[i7] != nil {
								cp.MachineConfig.MachineDisks[i4].DiskPartitions[i7] = new(DiskPartition)
								*cp.MachineConfig.MachineDisks[i4].DiskPartitions[i7] = *o.MachineConfig.MachineDisks[i4].DiskPartitions[i7]
							}
						}
					}
				}
			}
		}
		if o.MachineConfig.MachineInstall != nil {
			cp.MachineConfig.MachineInstall = new(InstallConfig)
			*cp.MachineConfig.MachineInstall = *o.MachineConfig.MachineInstall
			if o.MachineConfig.MachineInstall.InstallDiskSelector != nil {
				cp.MachineConfig.MachineInstall.InstallDiskSelector = new(InstallDiskSelector)
				*cp.MachineConfig.MachineInstall.InstallDiskSelector = *o.MachineConfig.MachineInstall.InstallDiskSelector
				if o.MachineConfig.MachineInstall.InstallDiskSelector.Size != nil {
					cp.MachineConfig.MachineInstall.InstallDiskSelector.Size = new(InstallDiskSizeMatcher)
					*cp.MachineConfig.MachineInstall.InstallDiskSelector.Size = *o.MachineConfig.MachineInstall.InstallDiskSelector.Size
				}
			}
			if o.MachineConfig.MachineInstall.InstallExtraKernelArgs != nil {
				cp.MachineConfig.MachineInstall.InstallExtraKernelArgs = make([]string, len(o.MachineConfig.MachineInstall.InstallExtraKernelArgs))
				copy(cp.MachineConfig.MachineInstall.InstallExtraKernelArgs, o.MachineConfig.MachineInstall.InstallExtraKernelArgs)
			}
			if o.MachineConfig.MachineInstall.InstallExtensions != nil {
				cp.MachineConfig.MachineInstall.InstallExtensions = make([]InstallExtensionConfig, len(o.MachineConfig.MachineInstall.InstallExtensions))
				copy(cp.MachineConfig.MachineInstall.InstallExtensions, o.MachineConfig.MachineInstall.InstallExtensions)
			}
			if o.MachineConfig.MachineInstall.InstallBootloader != nil {
				cp.MachineConfig.MachineInstall.InstallBootloader = new(bool)
				*cp.MachineConfig.MachineInstall.InstallBootloader = *o.MachineConfig.MachineInstall.InstallBootloader
			}
			if o.MachineConfig.MachineInstall.InstallWipe != nil {
				cp.MachineConfig.MachineInstall.InstallWipe = new(bool)
				*cp.MachineConfig.MachineInstall.InstallWipe = *o.MachineConfig.MachineInstall.InstallWipe
			}
			if o.MachineConfig.MachineInstall.InstallLegacyBIOSSupport != nil {
				cp.MachineConfig.MachineInstall.InstallLegacyBIOSSupport = new(bool)
				*cp.MachineConfig.MachineInstall.InstallLegacyBIOSSupport = *o.MachineConfig.MachineInstall.InstallLegacyBIOSSupport
			}
			if o.MachineConfig.MachineInstall.InstallGrubUseUKICmdline != nil {
				cp.MachineConfig.MachineInstall.InstallGrubUseUKICmdline = new(bool)
				*cp.MachineConfig.MachineInstall.InstallGrubUseUKICmdline = *o.MachineConfig.MachineInstall.InstallGrubUseUKICmdline
			}
		}
		if o.MachineConfig.MachineFiles != nil {
			cp.MachineConfig.MachineFiles = make([]*MachineFile, len(o.MachineConfig.MachineFiles))
			copy(cp.MachineConfig.MachineFiles, o.MachineConfig.MachineFiles)
			for i4 := range o.MachineConfig.MachineFiles {
				if o.MachineConfig.MachineFiles[i4] != nil {
					cp.MachineConfig.MachineFiles[i4] = new(MachineFile)
					*cp.MachineConfig.MachineFiles[i4] = *o.MachineConfig.MachineFiles[i4]
				}
			}
		}
		if o.MachineConfig.MachineEnv != nil {
			cp.MachineConfig.MachineEnv = make(map[string]string, len(o.MachineConfig.MachineEnv))
			for k4, v4 := range o.MachineConfig.MachineEnv {
				cp.MachineConfig.MachineEnv[k4] = v4
			}
		}
		if o.MachineConfig.MachineTime != nil {
			cp.MachineConfig.MachineTime = new(TimeConfig)
			*cp.MachineConfig.MachineTime = *o.MachineConfig.MachineTime
			if o.MachineConfig.MachineTime.TimeDisabled != nil {
				cp.MachineConfig.MachineTime.TimeDisabled = new(bool)
				*cp.MachineConfig.MachineTime.TimeDisabled = *o.MachineConfig.MachineTime.TimeDisabled
			}
			if o.MachineConfig.MachineTime.TimeServers != nil {
				cp.MachineConfig.MachineTime.TimeServers = make([]string, len(o.MachineConfig.MachineTime.TimeServers))
				copy(cp.MachineConfig.MachineTime.TimeServers, o.MachineConfig.MachineTime.TimeServers)
			}
		}
		if o.MachineConfig.MachineSysctls != nil {
			cp.MachineConfig.MachineSysctls = make(map[string]string, len(o.MachineConfig.MachineSysctls))
			for k4, v4 := range o.MachineConfig.MachineSysctls {
				cp.MachineConfig.MachineSysctls[k4] = v4
			}
		}
		if o.MachineConfig.MachineSysfs != nil {
			cp.MachineConfig.MachineSysfs = make(map[string]string, len(o.MachineConfig.MachineSysfs))
			for k4, v4 := range o.MachineConfig.MachineSysfs {
				cp.MachineConfig.MachineSysfs[k4] = v4
			}
		}
		if o.MachineConfig.MachineRegistries.RegistryMirrors != nil {
			cp.MachineConfig.MachineRegistries.RegistryMirrors = make(map[string]*RegistryMirrorConfig, len(o.MachineConfig.MachineRegistries.RegistryMirrors))
			for k5, v5 := range o.MachineConfig.MachineRegistries.RegistryMirrors {
				var cp_MachineConfig_MachineRegistries_RegistryMirrors_v5 *RegistryMirrorConfig
				if v5 != nil {
					cp_MachineConfig_MachineRegistries_RegistryMirrors_v5 = new(RegistryMirrorConfig)
					*cp_MachineConfig_MachineRegistries_RegistryMirrors_v5 = *v5
					if v5.MirrorEndpoints != nil {
						cp_MachineConfig_MachineRegistries_RegistryMirrors_v5.MirrorEndpoints = make([]string, len(v5.MirrorEndpoints))
						copy(cp_MachineConfig_MachineRegistries_RegistryMirrors_v5.MirrorEndpoints, v5.MirrorEndpoints)
					}
					if v5.MirrorOverridePath != nil {
						cp_MachineConfig_MachineRegistries_RegistryMirrors_v5.MirrorOverridePath = new(bool)
						*cp_MachineConfig_MachineRegistries_RegistryMirrors_v5.MirrorOverridePath = *v5.MirrorOverridePath
					}
					if v5.MirrorSkipFallback != nil {
						cp_MachineConfig_MachineRegistries_RegistryMirrors_v5.MirrorSkipFallback = new(bool)
						*cp_MachineConfig_MachineRegistries_RegistryMirrors_v5.MirrorSkipFallback = *v5.MirrorSkipFallback
					}
				}
				cp.MachineConfig.MachineRegistries.RegistryMirrors[k5] = cp_MachineConfig_MachineRegistries_RegistryMirrors_v5
			}
		}
		if o.MachineConfig.MachineRegistries.RegistryConfig != nil {
			cp.MachineConfig.MachineRegistries.RegistryConfig = make(map[string]*RegistryConfig, len(o.MachineConfig.MachineRegistries.RegistryConfig))
			for k5, v5 := range o.MachineConfig.MachineRegistries.RegistryConfig {
				var cp_MachineConfig_MachineRegistries_RegistryConfig_v5 *RegistryConfig
				if v5 != nil {
					cp_MachineConfig_MachineRegistries_RegistryConfig_v5 = new(RegistryConfig)
					*cp_MachineConfig_MachineRegistries_RegistryConfig_v5 = *v5
					if v5.RegistryTLS != nil {
						cp_MachineConfig_MachineRegistries_RegistryConfig_v5.RegistryTLS = new(RegistryTLSConfig)
						*cp_MachineConfig_MachineRegistries_RegistryConfig_v5.RegistryTLS = *v5.RegistryTLS
						if v5.RegistryTLS.TLSClientIdentity != nil {
							cp_MachineConfig_MachineRegistries_RegistryConfig_v5.RegistryTLS.TLSClientIdentity = v5.RegistryTLS.TLSClientIdentity.DeepCopy()
						}
						cp_MachineConfig_MachineRegistries_RegistryConfig_v5.RegistryTLS.TLSCA = v5.RegistryTLS.TLSCA.DeepCopy()
						if v5.RegistryTLS.TLSInsecureSkipVerify != nil {
							cp_MachineConfig_MachineRegistries_RegistryConfig_v5.RegistryTLS.TLSInsecureSkipVerify = new(bool)
							*cp_MachineConfig_MachineRegistries_RegistryConfig_v5.RegistryTLS.TLSInsecureSkipVerify = *v5.RegistryTLS.TLSInsecureSkipVerify
						}
					}
					if v5.RegistryAuth != nil {
						cp_MachineConfig_MachineRegistries_RegistryConfig_v5.RegistryAuth = new(RegistryAuthConfig)
						*cp_MachineConfig_MachineRegistries_RegistryConfig_v5.RegistryAuth = *v5.RegistryAuth
					}
				}
				cp.MachineConfig.MachineRegistries.RegistryConfig[k5] = cp_MachineConfig_MachineRegistries_RegistryConfig_v5
			}
		}
		if o.MachineConfig.MachineSystemDiskEncryption != nil {
			cp.MachineConfig.MachineSystemDiskEncryption = new(SystemDiskEncryptionConfig)
			*cp.MachineConfig.MachineSystemDiskEncryption = *o.MachineConfig.MachineSystemDiskEncryption
			if o.MachineConfig.MachineSystemDiskEncryption.StatePartition != nil {
				cp.MachineConfig.MachineSystemDiskEncryption.StatePartition = new(EncryptionConfig)
				*cp.MachineConfig.MachineSystemDiskEncryption.StatePartition = *o.MachineConfig.MachineSystemDiskEncryption.StatePartition
				if o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys != nil {
					cp.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys = make([]*EncryptionKey, len(o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys))
					copy(cp.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys, o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys)
					for i8 := range o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys {
						if o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8] != nil {
							cp.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8] = new(EncryptionKey)
							*cp.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8] = *o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8]
							if o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyStatic != nil {
								cp.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyStatic = new(EncryptionKeyStatic)
								*cp.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyStatic = *o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyStatic
							}
							if o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyNodeID != nil {
								cp.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyNodeID = new(EncryptionKeyNodeID)
								*cp.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyNodeID = *o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyNodeID
							}
							if o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyKMS != nil {
								cp.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyKMS = new(EncryptionKeyKMS)
								*cp.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyKMS = *o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyKMS
							}
							if o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyTPM != nil {
								cp.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyTPM = new(EncryptionKeyTPM)
								*cp.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyTPM = *o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyTPM
								if o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyTPM.TPMCheckSecurebootStatusOnEnroll != nil {
									cp.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyTPM.TPMCheckSecurebootStatusOnEnroll = new(bool)
									*cp.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyTPM.TPMCheckSecurebootStatusOnEnroll = *o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyTPM.TPMCheckSecurebootStatusOnEnroll
								}
							}
						}
					}
				}
				if o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionPerfOptions != nil {
					cp.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionPerfOptions = make([]string, len(o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionPerfOptions))
					copy(cp.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionPerfOptions, o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionPerfOptions)
				}
			}
			if o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition != nil {
				cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition = new(EncryptionConfig)
				*cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition = *o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition
				if o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys != nil {
					cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys = make([]*EncryptionKey, len(o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys))
					copy(cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys, o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys)
					for i8 := range o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys {
						if o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8] != nil {
							cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8] = new(EncryptionKey)
							*cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8] = *o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8]
							if o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyStatic != nil {
								cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyStatic = new(EncryptionKeyStatic)
								*cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyStatic = *o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyStatic
							}
							if o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyNodeID != nil {
								cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyNodeID = new(EncryptionKeyNodeID)
								*cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyNodeID = *o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyNodeID
							}
							if o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyKMS != nil {
								cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyKMS = new(EncryptionKeyKMS)
								*cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyKMS = *o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyKMS
							}
							if o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyTPM != nil {
								cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyTPM = new(EncryptionKeyTPM)
								*cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyTPM = *o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyTPM
								if o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyTPM.TPMCheckSecurebootStatusOnEnroll != nil {
									cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyTPM.TPMCheckSecurebootStatusOnEnroll = new(bool)
									*cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyTPM.TPMCheckSecurebootStatusOnEnroll = *o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyTPM.TPMCheckSecurebootStatusOnEnroll
								}
							}
						}
					}
				}
				if o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionPerfOptions != nil {
					cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionPerfOptions = make([]string, len(o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionPerfOptions))
					copy(cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionPerfOptions, o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionPerfOptions)
				}
			}
		}
		if o.MachineConfig.MachineFeatures != nil {
			cp.MachineConfig.MachineFeatures = new(FeaturesConfig)
			*cp.MachineConfig.MachineFeatures = *o.MachineConfig.MachineFeatures
			if o.MachineConfig.MachineFeatures.RBAC != nil {
				cp.MachineConfig.MachineFeatures.RBAC = new(bool)
				*cp.MachineConfig.MachineFeatures.RBAC = *o.MachineConfig.MachineFeatures.RBAC
			}
			if o.MachineConfig.MachineFeatures.StableHostname != nil {
				cp.MachineConfig.MachineFeatures.StableHostname = new(bool)
				*cp.MachineConfig.MachineFeatures.StableHostname = *o.MachineConfig.MachineFeatures.StableHostname
			}
			if o.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig != nil {
				cp.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig = new(KubernetesTalosAPIAccessConfig)
				*cp.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig = *o.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig
				if o.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig.AccessEnabled != nil {
					cp.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig.AccessEnabled = new(bool)
					*cp.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig.AccessEnabled = *o.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig.AccessEnabled
				}
				if o.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig.AccessAllowedRoles != nil {
					cp.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig.AccessAllowedRoles = make([]string, len(o.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig.AccessAllowedRoles))
					copy(cp.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig.AccessAllowedRoles, o.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig.AccessAllowedRoles)
				}
				if o.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig.AccessAllowedKubernetesNamespaces != nil {
					cp.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig.AccessAllowedKubernetesNamespaces = make([]string, len(o.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig.AccessAllowedKubernetesNamespaces))
					copy(cp.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig.AccessAllowedKubernetesNamespaces, o.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig.AccessAllowedKubernetesNamespaces)
				}
			}
			if o.MachineConfig.MachineFeatures.ApidCheckExtKeyUsage != nil {
				cp.MachineConfig.MachineFeatures.ApidCheckExtKeyUsage = new(bool)
				*cp.MachineConfig.MachineFeatures.ApidCheckExtKeyUsage = *o.MachineConfig.MachineFeatures.ApidCheckExtKeyUsage
			}
			if o.MachineConfig.MachineFeatures.DiskQuotaSupport != nil {
				cp.MachineConfig.MachineFeatures.DiskQuotaSupport = new(bool)
				*cp.MachineConfig.MachineFeatures.DiskQuotaSupport = *o.MachineConfig.MachineFeatures.DiskQuotaSupport
			}
			if o.MachineConfig.MachineFeatures.KubePrismSupport != nil {
				cp.MachineConfig.MachineFeatures.KubePrismSupport = new(KubePrism)
				*cp.MachineConfig.MachineFeatures.KubePrismSupport = *o.MachineConfig.MachineFeatures.KubePrismSupport
				if o.MachineConfig.MachineFeatures.KubePrismSupport.ServerEnabled != nil {
					cp.MachineConfig.MachineFeatures.KubePrismSupport.ServerEnabled = new(bool)
					*cp.MachineConfig.MachineFeatures.KubePrismSupport.ServerEnabled = *o.MachineConfig.MachineFeatures.KubePrismSupport.ServerEnabled
				}
			}
			if o.MachineConfig.MachineFeatures.HostDNSSupport != nil {
				cp.MachineConfig.MachineFeatures.HostDNSSupport = new(HostDNSConfig)
				*cp.MachineConfig.MachineFeatures.HostDNSSupport = *o.MachineConfig.MachineFeatures.HostDNSSupport
				if o.MachineConfig.MachineFeatures.HostDNSSupport.HostDNSEnabled != nil {
					cp.MachineConfig.MachineFeatures.HostDNSSupport.HostDNSEnabled = new(bool)
					*cp.MachineConfig.MachineFeatures.HostDNSSupport.HostDNSEnabled = *o.MachineConfig.MachineFeatures.HostDNSSupport.HostDNSEnabled
				}
				if o.MachineConfig.MachineFeatures.HostDNSSupport.HostDNSForwardKubeDNSToHost != nil {
					cp.MachineConfig.MachineFeatures.HostDNSSupport.HostDNSForwardKubeDNSToHost = new(bool)
					*cp.MachineConfig.MachineFeatures.HostDNSSupport.HostDNSForwardKubeDNSToHost = *o.MachineConfig.MachineFeatures.HostDNSSupport.HostDNSForwardKubeDNSToHost
				}
				if o.MachineConfig.MachineFeatures.HostDNSSupport.HostDNSResolveMemberNames != nil {
					cp.MachineConfig.MachineFeatures.HostDNSSupport.HostDNSResolveMemberNames = new(bool)
					*cp.MachineConfig.MachineFeatures.HostDNSSupport.HostDNSResolveMemberNames = *o.MachineConfig.MachineFeatures.HostDNSSupport.HostDNSResolveMemberNames
				}
			}
			if o.MachineConfig.MachineFeatures.ImageCacheSupport != nil {
				cp.MachineConfig.MachineFeatures.ImageCacheSupport = new(ImageCacheConfig)
				*cp.MachineConfig.MachineFeatures.ImageCacheSupport = *o.MachineConfig.MachineFeatures.ImageCacheSupport
				if o.MachineConfig.MachineFeatures.ImageCacheSupport.CacheLocalEnabled != nil {
					cp.MachineConfig.MachineFeatures.ImageCacheSupport.CacheLocalEnabled = new(bool)
					*cp.MachineConfig.MachineFeatures.ImageCacheSupport.CacheLocalEnabled = *o.MachineConfig.MachineFeatures.ImageCacheSupport.CacheLocalEnabled
				}
			}
		}
		if o.MachineConfig.MachineUdev != nil {
			cp.MachineConfig.MachineUdev = new(UdevConfig)
			*cp.MachineConfig.MachineUdev = *o.MachineConfig.MachineUdev
			if o.MachineConfig.MachineUdev.UdevRules != nil {
				cp.MachineConfig.MachineUdev.UdevRules = make([]string, len(o.MachineConfig.MachineUdev.UdevRules))
				copy(cp.MachineConfig.MachineUdev.UdevRules, o.MachineConfig.MachineUdev.UdevRules)
			}
		}
		if o.MachineConfig.MachineLogging != nil {
			cp.MachineConfig.MachineLogging = new(LoggingConfig)
			*cp.MachineConfig.MachineLogging = *o.MachineConfig.MachineLogging
			if o.MachineConfig.MachineLogging.LoggingDestinations != nil {
				cp.MachineConfig.MachineLogging.LoggingDestinations = make([]LoggingDestination, len(o.MachineConfig.MachineLogging.LoggingDestinations))
				copy(cp.MachineConfig.MachineLogging.LoggingDestinations, o.MachineConfig.MachineLogging.LoggingDestinations)
				for i6 := range o.MachineConfig.MachineLogging.LoggingDestinations {
					if o.MachineConfig.MachineLogging.LoggingDestinations[i6].LoggingEndpoint != nil {
						cp.MachineConfig.MachineLogging.LoggingDestinations[i6].LoggingEndpoint = o.MachineConfig.MachineLogging.LoggingDestinations[i6].LoggingEndpoint.DeepCopy()
					}
					if o.MachineConfig.MachineLogging.LoggingDestinations[i6].LoggingExtraTags != nil {
						cp.MachineConfig.MachineLogging.LoggingDestinations[i6].LoggingExtraTags = make(map[string]string, len(o.MachineConfig.MachineLogging.LoggingDestinations[i6].LoggingExtraTags))
						for k8, v8 := range o.MachineConfig.MachineLogging.LoggingDestinations[i6].LoggingExtraTags {
							cp.MachineConfig.MachineLogging.LoggingDestinations[i6].LoggingExtraTags[k8] = v8
						}
					}
				}
			}
		}
		if o.MachineConfig.MachineKernel != nil {
			cp.MachineConfig.MachineKernel = new(KernelConfig)
			*cp.MachineConfig.MachineKernel = *o.MachineConfig.MachineKernel
			if o.MachineConfig.MachineKernel.KernelModules != nil {
				cp.MachineConfig.MachineKernel.KernelModules = make([]*KernelModuleConfig, len(o.MachineConfig.MachineKernel.KernelModules))
				copy(cp.MachineConfig.MachineKernel.KernelModules, o.MachineConfig.MachineKernel.KernelModules)
				for i6 := range o.MachineConfig.MachineKernel.KernelModules {
					if o.MachineConfig.MachineKernel.KernelModules[i6] != nil {
						cp.MachineConfig.MachineKernel.KernelModules[i6] = new(KernelModuleConfig)
						*cp.MachineConfig.MachineKernel.KernelModules[i6] = *o.MachineConfig.MachineKernel.KernelModules[i6]
						if o.MachineConfig.MachineKernel.KernelModules[i6].ModuleParameters != nil {
							cp.MachineConfig.MachineKernel.KernelModules[i6].ModuleParameters = make([]string, len(o.MachineConfig.MachineKernel.KernelModules[i6].ModuleParameters))
							copy(cp.MachineConfig.MachineKernel.KernelModules[i6].ModuleParameters, o.MachineConfig.MachineKernel.KernelModules[i6].ModuleParameters)
						}
					}
				}
			}
		}
		if o.MachineConfig.MachineSeccompProfiles != nil {
			cp.MachineConfig.MachineSeccompProfiles = make([]*MachineSeccompProfile, len(o.MachineConfig.MachineSeccompProfiles))
			copy(cp.MachineConfig.MachineSeccompProfiles, o.MachineConfig.MachineSeccompProfiles)
			for i4 := range o.MachineConfig.MachineSeccompProfiles {
				if o.MachineConfig.MachineSeccompProfiles[i4] != nil {
					cp.MachineConfig.MachineSeccompProfiles[i4] = new(MachineSeccompProfile)
					*cp.MachineConfig.MachineSeccompProfiles[i4] = *o.MachineConfig.MachineSeccompProfiles[i4]
					{
						retV := o.MachineConfig.MachineSeccompProfiles[i4].MachineSeccompProfileValue.DeepCopy()
						cp.MachineConfig.MachineSeccompProfiles[i4].MachineSeccompProfileValue = *retV
					}
				}
			}
		}
		{
			retV := o.MachineConfig.MachineBaseRuntimeSpecOverrides.DeepCopy()
			cp.MachineConfig.MachineBaseRuntimeSpecOverrides = *retV
		}
	}
	if o.ClusterConfig != nil {
		cp.ClusterConfig = new(ClusterConfig)
		*cp.ClusterConfig = *o.ClusterConfig
		if o.ClusterConfig.ClusterDiscoveryConfig != nil {
			cp.ClusterConfig.ClusterDiscoveryConfig = new(ClusterDiscoveryConfig)
			*cp.ClusterConfig.ClusterDiscoveryConfig = *o.ClusterConfig.ClusterDiscoveryConfig
			if o.ClusterConfig.ClusterDiscoveryConfig.DiscoveryEnabled != nil {
				cp.ClusterConfig.ClusterDiscoveryConfig.DiscoveryEnabled = new(bool)
				*cp.ClusterConfig.ClusterDiscoveryConfig.DiscoveryEnabled = *o.ClusterConfig.ClusterDiscoveryConfig.DiscoveryEnabled
			}
			if o.ClusterConfig.ClusterDiscoveryConfig.DiscoveryRegistries.RegistryKubernetes.RegistryDisabled != nil {
				cp.ClusterConfig.ClusterDiscoveryConfig.DiscoveryRegistries.RegistryKubernetes.RegistryDisabled = new(bool)
				*cp.ClusterConfig.ClusterDiscoveryConfig.DiscoveryRegistries.RegistryKubernetes.RegistryDisabled = *o.ClusterConfig.ClusterDiscoveryConfig.DiscoveryRegistries.RegistryKubernetes.RegistryDisabled
			}
			if o.ClusterConfig.ClusterDiscoveryConfig.DiscoveryRegistries.RegistryService.RegistryDisabled != nil {
				cp.ClusterConfig.ClusterDiscoveryConfig.DiscoveryRegistries.RegistryService.RegistryDisabled = new(bool)
				*cp.ClusterConfig.ClusterDiscoveryConfig.DiscoveryRegistries.RegistryService.RegistryDisabled = *o.ClusterConfig.ClusterDiscoveryConfig.DiscoveryRegistries.RegistryService.RegistryDisabled
			}
		}
	}
	return &cp
}

// DeepCopy generates a deep copy of *Device.
func (o *Device) DeepCopy() *Device {
	var cp Device = *o
	if o.DeviceSelector != nil {
		cp.DeviceSelector = new(NetworkDeviceSelector)
		*cp.DeviceSelector = *o.DeviceSelector
		if o.DeviceSelector.NetworkDevicePhysical != nil {
			cp.DeviceSelector.NetworkDevicePhysical = new(bool)
			*cp.DeviceSelector.NetworkDevicePhysical = *o.DeviceSelector.NetworkDevicePhysical
		}
	}
	if o.DeviceAddresses != nil {
		cp.DeviceAddresses = make([]string, len(o.DeviceAddresses))
		copy(cp.DeviceAddresses, o.DeviceAddresses)
	}
	if o.DeviceRoutes != nil {
		cp.DeviceRoutes = make([]*Route, len(o.DeviceRoutes))
		copy(cp.DeviceRoutes, o.DeviceRoutes)
		for i2 := range o.DeviceRoutes {
			if o.DeviceRoutes[i2] != nil {
				cp.DeviceRoutes[i2] = new(Route)
				*cp.DeviceRoutes[i2] = *o.DeviceRoutes[i2]
			}
		}
	}
	if o.DeviceBond != nil {
		cp.DeviceBond = new(Bond)
		*cp.DeviceBond = *o.DeviceBond
		if o.DeviceBond.BondInterfaces != nil {
			cp.DeviceBond.BondInterfaces = make([]string, len(o.DeviceBond.BondInterfaces))
			copy(cp.DeviceBond.BondInterfaces, o.DeviceBond.BondInterfaces)
		}
		if o.DeviceBond.BondDeviceSelectors != nil {
			cp.DeviceBond.BondDeviceSelectors = make([]NetworkDeviceSelector, len(o.DeviceBond.BondDeviceSelectors))
			copy(cp.DeviceBond.BondDeviceSelectors, o.DeviceBond.BondDeviceSelectors)
			for i4 := range o.DeviceBond.BondDeviceSelectors {
				if o.DeviceBond.BondDeviceSelectors[i4].NetworkDevicePhysical != nil {
					cp.DeviceBond.BondDeviceSelectors[i4].NetworkDevicePhysical = new(bool)
					*cp.DeviceBond.BondDeviceSelectors[i4].NetworkDevicePhysical = *o.DeviceBond.BondDeviceSelectors[i4].NetworkDevicePhysical
				}
			}
		}
		if o.DeviceBond.BondARPIPTarget != nil {
			cp.DeviceBond.BondARPIPTarget = make([]string, len(o.DeviceBond.BondARPIPTarget))
			copy(cp.DeviceBond.BondARPIPTarget, o.DeviceBond.BondARPIPTarget)
		}
		if o.DeviceBond.BondUseCarrier != nil {
			cp.DeviceBond.BondUseCarrier = new(bool)
			*cp.DeviceBond.BondUseCarrier = *o.DeviceBond.BondUseCarrier
		}
	}
	if o.DeviceBridge != nil {
		cp.DeviceBridge = new(Bridge)
		*cp.DeviceBridge = *o.DeviceBridge
		if o.DeviceBridge.BridgedInterfaces != nil {
			cp.DeviceBridge.BridgedInterfaces = make([]string, len(o.DeviceBridge.BridgedInterfaces))
			copy(cp.DeviceBridge.BridgedInterfaces, o.DeviceBridge.BridgedInterfaces)
		}
		if o.DeviceBridge.BridgeSTP != nil {
			cp.DeviceBridge.BridgeSTP = new(STP)
			*cp.DeviceBridge.BridgeSTP = *o.DeviceBridge.BridgeSTP
			if o.DeviceBridge.BridgeSTP.STPEnabled != nil {
				cp.DeviceBridge.BridgeSTP.STPEnabled = new(bool)
				*cp.DeviceBridge.BridgeSTP.STPEnabled = *o.DeviceBridge.BridgeSTP.STPEnabled
			}
		}
		if o.DeviceBridge.BridgeVLAN != nil {
			cp.DeviceBridge.BridgeVLAN = new(BridgeVLAN)
			*cp.DeviceBridge.BridgeVLAN = *o.DeviceBridge.BridgeVLAN
			if o.DeviceBridge.BridgeVLAN.BridgeVLANFiltering != nil {
				cp.DeviceBridge.BridgeVLAN.BridgeVLANFiltering = new(bool)
				*cp.DeviceBridge.BridgeVLAN.BridgeVLANFiltering = *o.DeviceBridge.BridgeVLAN.BridgeVLANFiltering
			}
		}
	}
	if o.DeviceBridgePort != nil {
		cp.DeviceBridgePort = new(BridgePort)
		*cp.DeviceBridgePort = *o.DeviceBridgePort
	}
	if o.DeviceVlans != nil {
		cp.DeviceVlans = make([]*Vlan, len(o.DeviceVlans))
		copy(cp.DeviceVlans, o.DeviceVlans)
		for i2 := range o.DeviceVlans {
			if o.DeviceVlans[i2] != nil {
				cp.DeviceVlans[i2] = new(Vlan)
				*cp.DeviceVlans[i2] = *o.DeviceVlans[i2]
				if o.DeviceVlans[i2].VlanAddresses != nil {
					cp.DeviceVlans[i2].VlanAddresses = make([]string, len(o.DeviceVlans[i2].VlanAddresses))
					copy(cp.DeviceVlans[i2].VlanAddresses, o.DeviceVlans[i2].VlanAddresses)
				}
				if o.DeviceVlans[i2].VlanRoutes != nil {
					cp.DeviceVlans[i2].VlanRoutes = make([]*Route, len(o.DeviceVlans[i2].VlanRoutes))
					copy(cp.DeviceVlans[i2].VlanRoutes, o.DeviceVlans[i2].VlanRoutes)
					for i5 := range o.DeviceVlans[i2].VlanRoutes {
						if o.DeviceVlans[i2].VlanRoutes[i5] != nil {
							cp.DeviceVlans[i2].VlanRoutes[i5] = new(Route)
							*cp.DeviceVlans[i2].VlanRoutes[i5] = *o.DeviceVlans[i2].VlanRoutes[i5]
						}
					}
				}
				if o.DeviceVlans[i2].VlanDHCP != nil {
					cp.DeviceVlans[i2].VlanDHCP = new(bool)
					*cp.DeviceVlans[i2].VlanDHCP = *o.DeviceVlans[i2].VlanDHCP
				}
				if o.DeviceVlans[i2].VlanVIP != nil {
					cp.DeviceVlans[i2].VlanVIP = new(DeviceVIPConfig)
					*cp.DeviceVlans[i2].VlanVIP = *o.DeviceVlans[i2].VlanVIP
					if o.DeviceVlans[i2].VlanVIP.EquinixMetalConfig != nil {
						cp.DeviceVlans[i2].VlanVIP.EquinixMetalConfig = new(VIPEquinixMetalConfig)
						*cp.DeviceVlans[i2].VlanVIP.EquinixMetalConfig = *o.DeviceVlans[i2].VlanVIP.EquinixMetalConfig
					}
					if o.DeviceVlans[i2].VlanVIP.HCloudConfig != nil {
						cp.DeviceVlans[i2].VlanVIP.HCloudConfig = new(VIPHCloudConfig)
						*cp.DeviceVlans[i2].VlanVIP.HCloudConfig = *o.DeviceVlans[i2].VlanVIP.HCloudConfig
					}
				}
				if o.DeviceVlans[i2].VlanDHCPOptions != nil {
					cp.DeviceVlans[i2].VlanDHCPOptions = new(DHCPOptions)
					*cp.DeviceVlans[i2].VlanDHCPOptions = *o.DeviceVlans[i2].VlanDHCPOptions
					if o.DeviceVlans[i2].VlanDHCPOptions.DHCPIPv4 != nil {
						cp.DeviceVlans[i2].VlanDHCPOptions.DHCPIPv4 = new(bool)
						*cp.DeviceVlans[i2].VlanDHCPOptions.DHCPIPv4 = *o.DeviceVlans[i2].VlanDHCPOptions.DHCPIPv4
					}
					if o.DeviceVlans[i2].VlanDHCPOptions.DHCPIPv6 != nil {
						cp.DeviceVlans[i2].VlanDHCPOptions.DHCPIPv6 = new(bool)
						*cp.DeviceVlans[i2].VlanDHCPOptions.DHCPIPv6 = *o.DeviceVlans[i2].VlanDHCPOptions.DHCPIPv6
					}
				}
			}
		}
	}
	if o.DeviceDHCP != nil {
		cp.DeviceDHCP = new(bool)
		*cp.DeviceDHCP = *o.DeviceDHCP
	}
	if o.DeviceIgnore != nil {
		cp.DeviceIgnore = new(bool)
		*cp.DeviceIgnore = *o.DeviceIgnore
	}
	if o.DeviceDummy != nil {
		cp.DeviceDummy = new(bool)
		*cp.DeviceDummy = *o.DeviceDummy
	}
	if o.DeviceDHCPOptions != nil {
		cp.DeviceDHCPOptions = new(DHCPOptions)
		*cp.DeviceDHCPOptions = *o.DeviceDHCPOptions
		if o.DeviceDHCPOptions.DHCPIPv4 != nil {
			cp.DeviceDHCPOptions.DHCPIPv4 = new(bool)
			*cp.DeviceDHCPOptions.DHCPIPv4 = *o.DeviceDHCPOptions.DHCPIPv4
		}
		if o.DeviceDHCPOptions.DHCPIPv6 != nil {
			cp.DeviceDHCPOptions.DHCPIPv6 = new(bool)
			*cp.DeviceDHCPOptions.DHCPIPv6 = *o.DeviceDHCPOptions.DHCPIPv6
		}
	}
	if o.DeviceWireguardConfig != nil {
		cp.DeviceWireguardConfig = new(DeviceWireguardConfig)
		*cp.DeviceWireguardConfig = *o.DeviceWireguardConfig
		if o.DeviceWireguardConfig.WireguardPeers != nil {
			cp.DeviceWireguardConfig.WireguardPeers = make([]*DeviceWireguardPeer, len(o.DeviceWireguardConfig.WireguardPeers))
			copy(cp.DeviceWireguardConfig.WireguardPeers, o.DeviceWireguardConfig.WireguardPeers)
			for i4 := range o.DeviceWireguardConfig.WireguardPeers {
				if o.DeviceWireguardConfig.WireguardPeers[i4] != nil {
					cp.DeviceWireguardConfig.WireguardPeers[i4] = new(DeviceWireguardPeer)
					*cp.DeviceWireguardConfig.WireguardPeers[i4] = *o.DeviceWireguardConfig.WireguardPeers[i4]
					if o.DeviceWireguardConfig.WireguardPeers[i4].WireguardAllowedIPs != nil {
						cp.DeviceWireguardConfig.WireguardPeers[i4].WireguardAllowedIPs = make([]string, len(o.DeviceWireguardConfig.WireguardPeers[i4].WireguardAllowedIPs))
						copy(cp.DeviceWireguardConfig.WireguardPeers[i4].WireguardAllowedIPs, o.DeviceWireguardConfig.WireguardPeers[i4].WireguardAllowedIPs)
					}
				}
			}
		}
	}
	if o.DeviceVIPConfig != nil {
		cp.DeviceVIPConfig = new(DeviceVIPConfig)
		*cp.DeviceVIPConfig = *o.DeviceVIPConfig
		if o.DeviceVIPConfig.EquinixMetalConfig != nil {
			cp.DeviceVIPConfig.EquinixMetalConfig = new(VIPEquinixMetalConfig)
			*cp.DeviceVIPConfig.EquinixMetalConfig = *o.DeviceVIPConfig.EquinixMetalConfig
		}
		if o.DeviceVIPConfig.HCloudConfig != nil {
			cp.DeviceVIPConfig.HCloudConfig = new(VIPHCloudConfig)
			*cp.DeviceVIPConfig.HCloudConfig = *o.DeviceVIPConfig.HCloudConfig
		}
	}
	return &cp
}

// DeepCopy generates a deep copy of *ArgValue.
func (o *ArgValue) DeepCopy() *ArgValue {
	var cp ArgValue = *o
	if o.listValue != nil {
		cp.listValue = make([]string, len(o.listValue))
		copy(cp.listValue, o.listValue)
	}
	return &cp
}
