// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// Code generated by "deep-copy -type Config -type Device -type ArgValue -pointer-receiver -header-file ../../../../../hack/boilerplate.txt -o deep_copy.generated.go ."; DO NOT EDIT.

package v1alpha1

import (
	"github.com/siderolabs/crypto/x509"
)

// DeepCopy generates a deep copy of *Config.
func (o *Config) DeepCopy() *Config {
	var cp Config = *o
	if o.ConfigDebug != nil {
		cp.ConfigDebug = new(bool)
		*cp.ConfigDebug = *o.ConfigDebug
	}
	if o.ConfigPersist != nil {
		cp.ConfigPersist = new(bool)
		*cp.ConfigPersist = *o.ConfigPersist
	}
	if o.MachineConfig != nil {
		cp.MachineConfig = new(MachineConfig)
		*cp.MachineConfig = *o.MachineConfig
		if o.MachineConfig.MachineCA != nil {
			cp.MachineConfig.MachineCA = o.MachineConfig.MachineCA.DeepCopy()
		}
		if o.MachineConfig.MachineAcceptedCAs != nil {
			cp.MachineConfig.MachineAcceptedCAs = make([]*x509.PEMEncodedCertificate, len(o.MachineConfig.MachineAcceptedCAs))
			copy(cp.MachineConfig.MachineAcceptedCAs, o.MachineConfig.MachineAcceptedCAs)
			for i4 := range o.MachineConfig.MachineAcceptedCAs {
				if o.MachineConfig.MachineAcceptedCAs[i4] != nil {
					cp.MachineConfig.MachineAcceptedCAs[i4] = o.MachineConfig.MachineAcceptedCAs[i4].DeepCopy()
				}
			}
		}
		if o.MachineConfig.MachineCertSANs != nil {
			cp.MachineConfig.MachineCertSANs = make([]string, len(o.MachineConfig.MachineCertSANs))
			copy(cp.MachineConfig.MachineCertSANs, o.MachineConfig.MachineCertSANs)
		}
		if o.MachineConfig.MachineControlPlane != nil {
			cp.MachineConfig.MachineControlPlane = new(MachineControlPlaneConfig)
			*cp.MachineConfig.MachineControlPlane = *o.MachineConfig.MachineControlPlane
			if o.MachineConfig.MachineControlPlane.MachineControllerManager != nil {
				cp.MachineConfig.MachineControlPlane.MachineControllerManager = new(MachineControllerManagerConfig)
				*cp.MachineConfig.MachineControlPlane.MachineControllerManager = *o.MachineConfig.MachineControlPlane.MachineControllerManager
				if o.MachineConfig.MachineControlPlane.MachineControllerManager.MachineControllerManagerDisabled != nil {
					cp.MachineConfig.MachineControlPlane.MachineControllerManager.MachineControllerManagerDisabled = new(bool)
					*cp.MachineConfig.MachineControlPlane.MachineControllerManager.MachineControllerManagerDisabled = *o.MachineConfig.MachineControlPlane.MachineControllerManager.MachineControllerManagerDisabled
				}
			}
			if o.MachineConfig.MachineControlPlane.MachineScheduler != nil {
				cp.MachineConfig.MachineControlPlane.MachineScheduler = new(MachineSchedulerConfig)
				*cp.MachineConfig.MachineControlPlane.MachineScheduler = *o.MachineConfig.MachineControlPlane.MachineScheduler
				if o.MachineConfig.MachineControlPlane.MachineScheduler.MachineSchedulerDisabled != nil {
					cp.MachineConfig.MachineControlPlane.MachineScheduler.MachineSchedulerDisabled = new(bool)
					*cp.MachineConfig.MachineControlPlane.MachineScheduler.MachineSchedulerDisabled = *o.MachineConfig.MachineControlPlane.MachineScheduler.MachineSchedulerDisabled
				}
			}
		}
		if o.MachineConfig.MachineKubelet != nil {
			cp.MachineConfig.MachineKubelet = new(KubeletConfig)
			*cp.MachineConfig.MachineKubelet = *o.MachineConfig.MachineKubelet
			if o.MachineConfig.MachineKubelet.KubeletClusterDNS != nil {
				cp.MachineConfig.MachineKubelet.KubeletClusterDNS = make([]string, len(o.MachineConfig.MachineKubelet.KubeletClusterDNS))
				copy(cp.MachineConfig.MachineKubelet.KubeletClusterDNS, o.MachineConfig.MachineKubelet.KubeletClusterDNS)
			}
			if o.MachineConfig.MachineKubelet.KubeletExtraArgs != nil {
				cp.MachineConfig.MachineKubelet.KubeletExtraArgs = make(map[string]ArgValue, len(o.MachineConfig.MachineKubelet.KubeletExtraArgs))
				for k6, v6 := range o.MachineConfig.MachineKubelet.KubeletExtraArgs {
					var cp_MachineConfig_MachineKubelet_KubeletExtraArgs_v6 ArgValue
					{
						retV := v6.DeepCopy()
						cp_MachineConfig_MachineKubelet_KubeletExtraArgs_v6 = *retV
					}
					cp.MachineConfig.MachineKubelet.KubeletExtraArgs[k6] = cp_MachineConfig_MachineKubelet_KubeletExtraArgs_v6
				}
			}
			if o.MachineConfig.MachineKubelet.KubeletExtraMounts != nil {
				cp.MachineConfig.MachineKubelet.KubeletExtraMounts = make([]ExtraMount, len(o.MachineConfig.MachineKubelet.KubeletExtraMounts))
				copy(cp.MachineConfig.MachineKubelet.KubeletExtraMounts, o.MachineConfig.MachineKubelet.KubeletExtraMounts)
				for i6 := range o.MachineConfig.MachineKubelet.KubeletExtraMounts {
					if o.MachineConfig.MachineKubelet.KubeletExtraMounts[i6].Options != nil {
						cp.MachineConfig.MachineKubelet.KubeletExtraMounts[i6].Options = make([]string, len(o.MachineConfig.MachineKubelet.KubeletExtraMounts[i6].Options))
						copy(cp.MachineConfig.MachineKubelet.KubeletExtraMounts[i6].Options, o.MachineConfig.MachineKubelet.KubeletExtraMounts[i6].Options)
					}
					if o.MachineConfig.MachineKubelet.KubeletExtraMounts[i6].UIDMappings != nil {
						cp.MachineConfig.MachineKubelet.KubeletExtraMounts[i6].UIDMappings = make([]LinuxIDMapping, len(o.MachineConfig.MachineKubelet.KubeletExtraMounts[i6].UIDMappings))
						copy(cp.MachineConfig.MachineKubelet.KubeletExtraMounts[i6].UIDMappings, o.MachineConfig.MachineKubelet.KubeletExtraMounts[i6].UIDMappings)
					}
					if o.MachineConfig.MachineKubelet.KubeletExtraMounts[i6].GIDMappings != nil {
						cp.MachineConfig.MachineKubelet.KubeletExtraMounts[i6].GIDMappings = make([]LinuxIDMapping, len(o.MachineConfig.MachineKubelet.KubeletExtraMounts[i6].GIDMappings))
						copy(cp.MachineConfig.MachineKubelet.KubeletExtraMounts[i6].GIDMappings, o.MachineConfig.MachineKubelet.KubeletExtraMounts[i6].GIDMappings)
					}
				}
			}
			{
				retV := o.MachineConfig.MachineKubelet.KubeletExtraConfig.DeepCopy()
				cp.MachineConfig.MachineKubelet.KubeletExtraConfig = *retV
			}
			{
				retV := o.MachineConfig.MachineKubelet.KubeletCredentialProviderConfig.DeepCopy()
				cp.MachineConfig.MachineKubelet.KubeletCredentialProviderConfig = *retV
			}
			if o.MachineConfig.MachineKubelet.KubeletDefaultRuntimeSeccompProfileEnabled != nil {
				cp.MachineConfig.MachineKubelet.KubeletDefaultRuntimeSeccompProfileEnabled = new(bool)
				*cp.MachineConfig.MachineKubelet.KubeletDefaultRuntimeSeccompProfileEnabled = *o.MachineConfig.MachineKubelet.KubeletDefaultRuntimeSeccompProfileEnabled
			}
			if o.MachineConfig.MachineKubelet.KubeletRegisterWithFQDN != nil {
				cp.MachineConfig.MachineKubelet.KubeletRegisterWithFQDN = new(bool)
				*cp.MachineConfig.MachineKubelet.KubeletRegisterWithFQDN = *o.MachineConfig.MachineKubelet.KubeletRegisterWithFQDN
			}
			if o.MachineConfig.MachineKubelet.KubeletNodeIP != nil {
				cp.MachineConfig.MachineKubelet.KubeletNodeIP = new(KubeletNodeIPConfig)
				*cp.MachineConfig.MachineKubelet.KubeletNodeIP = *o.MachineConfig.MachineKubelet.KubeletNodeIP
				if o.MachineConfig.MachineKubelet.KubeletNodeIP.KubeletNodeIPValidSubnets != nil {
					cp.MachineConfig.MachineKubelet.KubeletNodeIP.KubeletNodeIPValidSubnets = make([]string, len(o.MachineConfig.MachineKubelet.KubeletNodeIP.KubeletNodeIPValidSubnets))
					copy(cp.MachineConfig.MachineKubelet.KubeletNodeIP.KubeletNodeIPValidSubnets, o.MachineConfig.MachineKubelet.KubeletNodeIP.KubeletNodeIPValidSubnets)
				}
			}
			if o.MachineConfig.MachineKubelet.KubeletSkipNodeRegistration != nil {
				cp.MachineConfig.MachineKubelet.KubeletSkipNodeRegistration = new(bool)
				*cp.MachineConfig.MachineKubelet.KubeletSkipNodeRegistration = *o.MachineConfig.MachineKubelet.KubeletSkipNodeRegistration
			}
			if o.MachineConfig.MachineKubelet.KubeletDisableManifestsDirectory != nil {
				cp.MachineConfig.MachineKubelet.KubeletDisableManifestsDirectory = new(bool)
				*cp.MachineConfig.MachineKubelet.KubeletDisableManifestsDirectory = *o.MachineConfig.MachineKubelet.KubeletDisableManifestsDirectory
			}
		}
		if o.MachineConfig.MachinePods != nil {
			cp.MachineConfig.MachinePods = make([]Unstructured, len(o.MachineConfig.MachinePods))
			copy(cp.MachineConfig.MachinePods, o.MachineConfig.MachinePods)
			for i4 := range o.MachineConfig.MachinePods {
				{
					retV := o.MachineConfig.MachinePods[i4].DeepCopy()
					cp.MachineConfig.MachinePods[i4] = *retV
				}
			}
		}
		if o.MachineConfig.MachineNetwork != nil {
			cp.MachineConfig.MachineNetwork = new(NetworkConfig)
			*cp.MachineConfig.MachineNetwork = *o.MachineConfig.MachineNetwork
			if o.MachineConfig.MachineNetwork.NetworkInterfaces != nil {
				cp.MachineConfig.MachineNetwork.NetworkInterfaces = make([]*Device, len(o.MachineConfig.MachineNetwork.NetworkInterfaces))
				copy(cp.MachineConfig.MachineNetwork.NetworkInterfaces, o.MachineConfig.MachineNetwork.NetworkInterfaces)
				for i6 := range o.MachineConfig.MachineNetwork.NetworkInterfaces {
					if o.MachineConfig.MachineNetwork.NetworkInterfaces[i6] != nil {
						cp.MachineConfig.MachineNetwork.NetworkInterfaces[i6] = o.MachineConfig.MachineNetwork.NetworkInterfaces[i6].DeepCopy()
					}
				}
			}
			if o.MachineConfig.MachineNetwork.NameServers != nil {
				cp.MachineConfig.MachineNetwork.NameServers = make([]string, len(o.MachineConfig.MachineNetwork.NameServers))
				copy(cp.MachineConfig.MachineNetwork.NameServers, o.MachineConfig.MachineNetwork.NameServers)
			}
			if o.MachineConfig.MachineNetwork.Searches != nil {
				cp.MachineConfig.MachineNetwork.Searches = make([]string, len(o.MachineConfig.MachineNetwork.Searches))
				copy(cp.MachineConfig.MachineNetwork.Searches, o.MachineConfig.MachineNetwork.Searches)
			}
			if o.MachineConfig.MachineNetwork.ExtraHostEntries != nil {
				cp.MachineConfig.MachineNetwork.ExtraHostEntries = make([]*ExtraHost, len(o.MachineConfig.MachineNetwork.ExtraHostEntries))
				copy(cp.MachineConfig.MachineNetwork.ExtraHostEntries, o.MachineConfig.MachineNetwork.ExtraHostEntries)
				for i6 := range o.MachineConfig.MachineNetwork.ExtraHostEntries {
					if o.MachineConfig.MachineNetwork.ExtraHostEntries[i6] != nil {
						cp.MachineConfig.MachineNetwork.ExtraHostEntries[i6] = new(ExtraHost)
						*cp.MachineConfig.MachineNetwork.ExtraHostEntries[i6] = *o.MachineConfig.MachineNetwork.ExtraHostEntries[i6]
						if o.MachineConfig.MachineNetwork.ExtraHostEntries[i6].HostAliases != nil {
							cp.MachineConfig.MachineNetwork.ExtraHostEntries[i6].HostAliases = make([]string, len(o.MachineConfig.MachineNetwork.ExtraHostEntries[i6].HostAliases))
							copy(cp.MachineConfig.MachineNetwork.ExtraHostEntries[i6].HostAliases, o.MachineConfig.MachineNetwork.ExtraHostEntries[i6].HostAliases)
						}
					}
				}
			}
			if o.MachineConfig.MachineNetwork.NetworkDisableSearchDomain != nil {
				cp.MachineConfig.MachineNetwork.NetworkDisableSearchDomain = new(bool)
				*cp.MachineConfig.MachineNetwork.NetworkDisableSearchDomain = *o.MachineConfig.MachineNetwork.NetworkDisableSearchDomain
			}
		}
		if o.MachineConfig.MachineDisks != nil {
			cp.MachineConfig.MachineDisks = make([]*MachineDisk, len(o.MachineConfig.MachineDisks))
			copy(cp.MachineConfig.MachineDisks, o.MachineConfig.MachineDisks)
			for i4 := range o.MachineConfig.MachineDisks {
				if o.MachineConfig.MachineDisks[i4] != nil {
					cp.MachineConfig.MachineDisks[i4] = new(MachineDisk)
					*cp.MachineConfig.MachineDisks[i4] = *o.MachineConfig.MachineDisks[i4]
					if o.MachineConfig.MachineDisks[i4].DiskPartitions != nil {
						cp.MachineConfig.MachineDisks[i4].DiskPartitions = make([]*DiskPartition, len(o.MachineConfig.MachineDisks[i4].DiskPartitions))
						copy(cp.MachineConfig.MachineDisks[i4].DiskPartitions, o.MachineConfig.MachineDisks[i4].DiskPartitions)
						for i7 := range o.MachineConfig.MachineDisks[i4].DiskPartitions {
							if o.MachineConfig.MachineDisks[i4].DiskPartitions[i7] != nil {
								cp.MachineConfig.MachineDisks[i4].DiskPartitions[i7] = new(DiskPartition)
								*cp.MachineConfig.MachineDisks[i4].DiskPartitions[i7] = *o.MachineConfig.MachineDisks[i4].DiskPartitions[i7]
							}
						}
					}
				}
			}
		}
		if o.MachineConfig.MachineInstall != nil {
			cp.MachineConfig.MachineInstall = new(InstallConfig)
			*cp.MachineConfig.MachineInstall = *o.MachineConfig.MachineInstall
			if o.MachineConfig.MachineInstall.InstallDiskSelector != nil {
				cp.MachineConfig.MachineInstall.InstallDiskSelector = new(InstallDiskSelector)
				*cp.MachineConfig.MachineInstall.InstallDiskSelector = *o.MachineConfig.MachineInstall.InstallDiskSelector
				if o.MachineConfig.MachineInstall.InstallDiskSelector.Size != nil {
					cp.MachineConfig.MachineInstall.InstallDiskSelector.Size = new(InstallDiskSizeMatcher)
					*cp.MachineConfig.MachineInstall.InstallDiskSelector.Size = *o.MachineConfig.MachineInstall.InstallDiskSelector.Size
				}
			}
			if o.MachineConfig.MachineInstall.InstallExtraKernelArgs != nil {
				cp.MachineConfig.MachineInstall.InstallExtraKernelArgs = make([]string, len(o.MachineConfig.MachineInstall.InstallExtraKernelArgs))
				copy(cp.MachineConfig.MachineInstall.InstallExtraKernelArgs, o.MachineConfig.MachineInstall.InstallExtraKernelArgs)
			}
			if o.MachineConfig.MachineInstall.InstallExtensions != nil {
				cp.MachineConfig.MachineInstall.InstallExtensions = make([]InstallExtensionConfig, len(o.MachineConfig.MachineInstall.InstallExtensions))
				copy(cp.MachineConfig.MachineInstall.InstallExtensions, o.MachineConfig.MachineInstall.InstallExtensions)
			}
			if o.MachineConfig.MachineInstall.InstallBootloader != nil {
				cp.MachineConfig.MachineInstall.InstallBootloader = new(bool)
				*cp.MachineConfig.MachineInstall.InstallBootloader = *o.MachineConfig.MachineInstall.InstallBootloader
			}
			if o.MachineConfig.MachineInstall.InstallWipe != nil {
				cp.MachineConfig.MachineInstall.InstallWipe = new(bool)
				*cp.MachineConfig.MachineInstall.InstallWipe = *o.MachineConfig.MachineInstall.InstallWipe
			}
			if o.MachineConfig.MachineInstall.InstallLegacyBIOSSupport != nil {
				cp.MachineConfig.MachineInstall.InstallLegacyBIOSSupport = new(bool)
				*cp.MachineConfig.MachineInstall.InstallLegacyBIOSSupport = *o.MachineConfig.MachineInstall.InstallLegacyBIOSSupport
			}
			if o.MachineConfig.MachineInstall.InstallGrubUseUKICmdline != nil {
				cp.MachineConfig.MachineInstall.InstallGrubUseUKICmdline = new(bool)
				*cp.MachineConfig.MachineInstall.InstallGrubUseUKICmdline = *o.MachineConfig.MachineInstall.InstallGrubUseUKICmdline
			}
		}
		if o.MachineConfig.MachineFiles != nil {
			cp.MachineConfig.MachineFiles = make([]*MachineFile, len(o.MachineConfig.MachineFiles))
			copy(cp.MachineConfig.MachineFiles, o.MachineConfig.MachineFiles)
			for i4 := range o.MachineConfig.MachineFiles {
				if o.MachineConfig.MachineFiles[i4] != nil {
					cp.MachineConfig.MachineFiles[i4] = new(MachineFile)
					*cp.MachineConfig.MachineFiles[i4] = *o.MachineConfig.MachineFiles[i4]
				}
			}
		}
		if o.MachineConfig.MachineEnv != nil {
			cp.MachineConfig.MachineEnv = make(map[string]string, len(o.MachineConfig.MachineEnv))
			for k4, v4 := range o.MachineConfig.MachineEnv {
				cp.MachineConfig.MachineEnv[k4] = v4
			}
		}
		if o.MachineConfig.MachineTime != nil {
			cp.MachineConfig.MachineTime = new(TimeConfig)
			*cp.MachineConfig.MachineTime = *o.MachineConfig.MachineTime
			if o.MachineConfig.MachineTime.TimeDisabled != nil {
				cp.MachineConfig.MachineTime.TimeDisabled = new(bool)
				*cp.MachineConfig.MachineTime.TimeDisabled = *o.MachineConfig.MachineTime.TimeDisabled
			}
			if o.MachineConfig.MachineTime.TimeServers != nil {
				cp.MachineConfig.MachineTime.TimeServers = make([]string, len(o.MachineConfig.MachineTime.TimeServers))
				copy(cp.MachineConfig.MachineTime.TimeServers, o.MachineConfig.MachineTime.TimeServers)
			}
		}
		if o.MachineConfig.MachineSysctls != nil {
			cp.MachineConfig.MachineSysctls = make(map[string]string, len(o.MachineConfig.MachineSysctls))
			for k4, v4 := range o.MachineConfig.MachineSysctls {
				cp.MachineConfig.MachineSysctls[k4] = v4
			}
		}
		if o.MachineConfig.MachineSysfs != nil {
			cp.MachineConfig.MachineSysfs = make(map[string]string, len(o.MachineConfig.MachineSysfs))
			for k4, v4 := range o.MachineConfig.MachineSysfs {
				cp.MachineConfig.MachineSysfs[k4] = v4
			}
		}
		if o.MachineConfig.MachineRegistries.RegistryMirrors != nil {
			cp.MachineConfig.MachineRegistries.RegistryMirrors = make(map[string]*RegistryMirrorConfig, len(o.MachineConfig.MachineRegistries.RegistryMirrors))
			for k5, v5 := range o.MachineConfig.MachineRegistries.RegistryMirrors {
				var cp_MachineConfig_MachineRegistries_RegistryMirrors_v5 *RegistryMirrorConfig
				if v5 != nil {
					cp_MachineConfig_MachineRegistries_RegistryMirrors_v5 = new(RegistryMirrorConfig)
					*cp_MachineConfig_MachineRegistries_RegistryMirrors_v5 = *v5
					if v5.MirrorEndpoints != nil {
						cp_MachineConfig_MachineRegistries_RegistryMirrors_v5.MirrorEndpoints = make([]string, len(v5.MirrorEndpoints))
						copy(cp_MachineConfig_MachineRegistries_RegistryMirrors_v5.MirrorEndpoints, v5.MirrorEndpoints)
					}
					if v5.MirrorOverridePath != nil {
						cp_MachineConfig_MachineRegistries_RegistryMirrors_v5.MirrorOverridePath = new(bool)
						*cp_MachineConfig_MachineRegistries_RegistryMirrors_v5.MirrorOverridePath = *v5.MirrorOverridePath
					}
					if v5.MirrorSkipFallback != nil {
						cp_MachineConfig_MachineRegistries_RegistryMirrors_v5.MirrorSkipFallback = new(bool)
						*cp_MachineConfig_MachineRegistries_RegistryMirrors_v5.MirrorSkipFallback = *v5.MirrorSkipFallback
					}
				}
				cp.MachineConfig.MachineRegistries.RegistryMirrors[k5] = cp_MachineConfig_MachineRegistries_RegistryMirrors_v5
			}
		}
		if o.MachineConfig.MachineRegistries.RegistryConfig != nil {
			cp.MachineConfig.MachineRegistries.RegistryConfig = make(map[string]*RegistryConfig, len(o.MachineConfig.MachineRegistries.RegistryConfig))
			for k5, v5 := range o.MachineConfig.MachineRegistries.RegistryConfig {
				var cp_MachineConfig_MachineRegistries_RegistryConfig_v5 *RegistryConfig
				if v5 != nil {
					cp_MachineConfig_MachineRegistries_RegistryConfig_v5 = new(RegistryConfig)
					*cp_MachineConfig_MachineRegistries_RegistryConfig_v5 = *v5
					if v5.RegistryTLS != nil {
						cp_MachineConfig_MachineRegistries_RegistryConfig_v5.RegistryTLS = new(RegistryTLSConfig)
						*cp_MachineConfig_MachineRegistries_RegistryConfig_v5.RegistryTLS = *v5.RegistryTLS
						if v5.RegistryTLS.TLSClientIdentity != nil {
							cp_MachineConfig_MachineRegistries_RegistryConfig_v5.RegistryTLS.TLSClientIdentity = v5.RegistryTLS.TLSClientIdentity.DeepCopy()
						}
						cp_MachineConfig_MachineRegistries_RegistryConfig_v5.RegistryTLS.TLSCA = v5.RegistryTLS.TLSCA.DeepCopy()
						if v5.RegistryTLS.TLSInsecureSkipVerify != nil {
							cp_MachineConfig_MachineRegistries_RegistryConfig_v5.RegistryTLS.TLSInsecureSkipVerify = new(bool)
							*cp_MachineConfig_MachineRegistries_RegistryConfig_v5.RegistryTLS.TLSInsecureSkipVerify = *v5.RegistryTLS.TLSInsecureSkipVerify
						}
					}
					if v5.RegistryAuth != nil {
						cp_MachineConfig_MachineRegistries_RegistryConfig_v5.RegistryAuth = new(RegistryAuthConfig)
						*cp_MachineConfig_MachineRegistries_RegistryConfig_v5.RegistryAuth = *v5.RegistryAuth
					}
				}
				cp.MachineConfig.MachineRegistries.RegistryConfig[k5] = cp_MachineConfig_MachineRegistries_RegistryConfig_v5
			}
		}
		if o.MachineConfig.MachineSystemDiskEncryption != nil {
			cp.MachineConfig.MachineSystemDiskEncryption = new(SystemDiskEncryptionConfig)
			*cp.MachineConfig.MachineSystemDiskEncryption = *o.MachineConfig.MachineSystemDiskEncryption
			if o.MachineConfig.MachineSystemDiskEncryption.StatePartition != nil {
				cp.MachineConfig.MachineSystemDiskEncryption.StatePartition = new(EncryptionConfig)
				*cp.MachineConfig.MachineSystemDiskEncryption.StatePartition = *o.MachineConfig.MachineSystemDiskEncryption.StatePartition
				if o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys != nil {
					cp.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys = make([]*EncryptionKey, len(o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys))
					copy(cp.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys, o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys)
					for i8 := range o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys {
						if o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8] != nil {
							cp.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8] = new(EncryptionKey)
							*cp.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8] = *o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8]
							if o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyStatic != nil {
								cp.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyStatic = new(EncryptionKeyStatic)
								*cp.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyStatic = *o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyStatic
							}
							if o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyNodeID != nil {
								cp.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyNodeID = new(EncryptionKeyNodeID)
								*cp.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyNodeID = *o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyNodeID
							}
							if o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyKMS != nil {
								cp.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyKMS = new(EncryptionKeyKMS)
								*cp.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyKMS = *o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyKMS
							}
							if o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyTPM != nil {
								cp.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyTPM = new(EncryptionKeyTPM)
								*cp.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyTPM = *o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyTPM
								if o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyTPM.TPMCheckSecurebootStatusOnEnroll != nil {
									cp.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyTPM.TPMCheckSecurebootStatusOnEnroll = new(bool)
									*cp.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyTPM.TPMCheckSecurebootStatusOnEnroll = *o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionKeys[i8].KeyTPM.TPMCheckSecurebootStatusOnEnroll
								}
							}
						}
					}
				}
				if o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionPerfOptions != nil {
					cp.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionPerfOptions = make([]string, len(o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionPerfOptions))
					copy(cp.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionPerfOptions, o.MachineConfig.MachineSystemDiskEncryption.StatePartition.EncryptionPerfOptions)
				}
			}
			if o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition != nil {
				cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition = new(EncryptionConfig)
				*cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition = *o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition
				if o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys != nil {
					cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys = make([]*EncryptionKey, len(o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys))
					copy(cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys, o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys)
					for i8 := range o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys {
						if o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8] != nil {
							cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8] = new(EncryptionKey)
							*cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8] = *o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8]
							if o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyStatic != nil {
								cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyStatic = new(EncryptionKeyStatic)
								*cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyStatic = *o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyStatic
							}
							if o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyNodeID != nil {
								cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyNodeID = new(EncryptionKeyNodeID)
								*cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyNodeID = *o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyNodeID
							}
							if o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyKMS != nil {
								cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyKMS = new(EncryptionKeyKMS)
								*cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyKMS = *o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyKMS
							}
							if o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyTPM != nil {
								cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyTPM = new(EncryptionKeyTPM)
								*cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyTPM = *o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyTPM
								if o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyTPM.TPMCheckSecurebootStatusOnEnroll != nil {
									cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyTPM.TPMCheckSecurebootStatusOnEnroll = new(bool)
									*cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyTPM.TPMCheckSecurebootStatusOnEnroll = *o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionKeys[i8].KeyTPM.TPMCheckSecurebootStatusOnEnroll
								}
							}
						}
					}
				}
				if o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionPerfOptions != nil {
					cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionPerfOptions = make([]string, len(o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionPerfOptions))
					copy(cp.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionPerfOptions, o.MachineConfig.MachineSystemDiskEncryption.EphemeralPartition.EncryptionPerfOptions)
				}
			}
		}
		if o.MachineConfig.MachineFeatures != nil {
			cp.MachineConfig.MachineFeatures = new(FeaturesConfig)
			*cp.MachineConfig.MachineFeatures = *o.MachineConfig.MachineFeatures
			if o.MachineConfig.MachineFeatures.RBAC != nil {
				cp.MachineConfig.MachineFeatures.RBAC = new(bool)
				*cp.MachineConfig.MachineFeatures.RBAC = *o.MachineConfig.MachineFeatures.RBAC
			}
			if o.MachineConfig.MachineFeatures.StableHostname != nil {
				cp.MachineConfig.MachineFeatures.StableHostname = new(bool)
				*cp.MachineConfig.MachineFeatures.StableHostname = *o.MachineConfig.MachineFeatures.StableHostname
			}
			if o.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig != nil {
				cp.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig = new(KubernetesTalosAPIAccessConfig)
				*cp.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig = *o.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig
				if o.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig.AccessEnabled != nil {
					cp.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig.AccessEnabled = new(bool)
					*cp.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig.AccessEnabled = *o.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig.AccessEnabled
				}
				if o.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig.AccessAllowedRoles != nil {
					cp.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig.AccessAllowedRoles = make([]string, len(o.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig.AccessAllowedRoles))
					copy(cp.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig.AccessAllowedRoles, o.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig.AccessAllowedRoles)
				}
				if o.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig.AccessAllowedKubernetesNamespaces != nil {
					cp.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig.AccessAllowedKubernetesNamespaces = make([]string, len(o.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig.AccessAllowedKubernetesNamespaces))
					copy(cp.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig.AccessAllowedKubernetesNamespaces, o.MachineConfig.MachineFeatures.KubernetesTalosAPIAccessConfig.AccessAllowedKubernetesNamespaces)
				}
			}
			if o.MachineConfig.MachineFeatures.ApidCheckExtKeyUsage != nil {
				cp.MachineConfig.MachineFeatures.ApidCheckExtKeyUsage = new(bool)
				*cp.MachineConfig.MachineFeatures.ApidCheckExtKeyUsage = *o.MachineConfig.MachineFeatures.ApidCheckExtKeyUsage
			}
			if o.MachineConfig.MachineFeatures.DiskQuotaSupport != nil {
				cp.MachineConfig.MachineFeatures.DiskQuotaSupport = new(bool)
				*cp.MachineConfig.MachineFeatures.DiskQuotaSupport = *o.MachineConfig.MachineFeatures.DiskQuotaSupport
			}
			if o.MachineConfig.MachineFeatures.KubePrismSupport != nil {
				cp.MachineConfig.MachineFeatures.KubePrismSupport = new(KubePrism)
				*cp.MachineConfig.MachineFeatures.KubePrismSupport = *o.MachineConfig.MachineFeatures.KubePrismSupport
				if o.MachineConfig.MachineFeatures.KubePrismSupport.ServerEnabled != nil {
					cp.MachineConfig.MachineFeatures.KubePrismSupport.ServerEnabled = new(bool)
					*cp.MachineConfig.MachineFeatures.KubePrismSupport.ServerEnabled = *o.MachineConfig.MachineFeatures.KubePrismSupport.ServerEnabled
				}
			}
			if o.MachineConfig.MachineFeatures.HostDNSSupport != nil {
				cp.MachineConfig.MachineFeatures.HostDNSSupport = new(HostDNSConfig)
				*cp.MachineConfig.MachineFeatures.HostDNSSupport = *o.MachineConfig.MachineFeatures.HostDNSSupport
				if o.MachineConfig.MachineFeatures.HostDNSSupport.HostDNSEnabled != nil {
					cp.MachineConfig.MachineFeatures.HostDNSSupport.HostDNSEnabled = new(bool)
					*cp.MachineConfig.MachineFeatures.HostDNSSupport.HostDNSEnabled = *o.MachineConfig.MachineFeatures.HostDNSSupport.HostDNSEnabled
				}
				if o.MachineConfig.MachineFeatures.HostDNSSupport.HostDNSForwardKubeDNSToHost != nil {
					cp.MachineConfig.MachineFeatures.HostDNSSupport.HostDNSForwardKubeDNSToHost = new(bool)
					*cp.MachineConfig.MachineFeatures.HostDNSSupport.HostDNSForwardKubeDNSToHost = *o.MachineConfig.MachineFeatures.HostDNSSupport.HostDNSForwardKubeDNSToHost
				}
				if o.MachineConfig.MachineFeatures.HostDNSSupport.HostDNSResolveMemberNames != nil {
					cp.MachineConfig.MachineFeatures.HostDNSSupport.HostDNSResolveMemberNames = new(bool)
					*cp.MachineConfig.MachineFeatures.HostDNSSupport.HostDNSResolveMemberNames = *o.MachineConfig.MachineFeatures.HostDNSSupport.HostDNSResolveMemberNames
				}
			}
			if o.MachineConfig.MachineFeatures.ImageCacheSupport != nil {
				cp.MachineConfig.MachineFeatures.ImageCacheSupport = new(ImageCacheConfig)
				*cp.MachineConfig.MachineFeatures.ImageCacheSupport = *o.MachineConfig.MachineFeatures.ImageCacheSupport
				if o.MachineConfig.MachineFeatures.ImageCacheSupport.CacheLocalEnabled != nil {
					cp.MachineConfig.MachineFeatures.ImageCacheSupport.CacheLocalEnabled = new(bool)
					*cp.MachineConfig.MachineFeatures.ImageCacheSupport.CacheLocalEnabled = *o.MachineConfig.MachineFeatures.ImageCacheSupport.CacheLocalEnabled
				}
			}
		}
		if o.MachineConfig.MachineUdev != nil {
			cp.MachineConfig.MachineUdev = new(UdevConfig)
			*cp.MachineConfig.MachineUdev = *o.MachineConfig.MachineUdev
			if o.MachineConfig.MachineUdev.UdevRules != nil {
				cp.MachineConfig.MachineUdev.UdevRules = make([]string, len(o.MachineConfig.MachineUdev.UdevRules))
				copy(cp.MachineConfig.MachineUdev.UdevRules, o.MachineConfig.MachineUdev.UdevRules)
			}
		}
		if o.MachineConfig.MachineLogging != nil {
			cp.MachineConfig.MachineLogging = new(LoggingConfig)
			*cp.MachineConfig.MachineLogging = *o.MachineConfig.MachineLogging
			if o.MachineConfig.MachineLogging.LoggingDestinations != nil {
				cp.MachineConfig.MachineLogging.LoggingDestinations = make([]LoggingDestination, len(o.MachineConfig.MachineLogging.LoggingDestinations))
				copy(cp.MachineConfig.MachineLogging.LoggingDestinations, o.MachineConfig.MachineLogging.LoggingDestinations)
				for i6 := range o.MachineConfig.MachineLogging.LoggingDestinations {
					if o.MachineConfig.MachineLogging.LoggingDestinations[i6].LoggingEndpoint != nil {
						cp.MachineConfig.MachineLogging.LoggingDestinations[i6].LoggingEndpoint = o.MachineConfig.MachineLogging.LoggingDestinations[i6].LoggingEndpoint.DeepCopy()
					}
					if o.MachineConfig.MachineLogging.LoggingDestinations[i6].LoggingExtraTags != nil {
						cp.MachineConfig.MachineLogging.LoggingDestinations[i6].LoggingExtraTags = make(map[string]string, len(o.MachineConfig.MachineLogging.LoggingDestinations[i6].LoggingExtraTags))
						for k8, v8 := range o.MachineConfig.MachineLogging.LoggingDestinations[i6].LoggingExtraTags {
							cp.MachineConfig.MachineLogging.LoggingDestinations[i6].LoggingExtraTags[k8] = v8
						}
					}
				}
			}
		}
		if o.MachineConfig.MachineKernel != nil {
			cp.MachineConfig.MachineKernel = new(KernelConfig)
			*cp.MachineConfig.MachineKernel = *o.MachineConfig.MachineKernel
			if o.MachineConfig.MachineKernel.KernelModules != nil {
				cp.MachineConfig.MachineKernel.KernelModules = make([]*KernelModuleConfig, len(o.MachineConfig.MachineKernel.KernelModules))
				copy(cp.MachineConfig.MachineKernel.KernelModules, o.MachineConfig.MachineKernel.KernelModules)
				for i6 := range o.MachineConfig.MachineKernel.KernelModules {
					if o.MachineConfig.MachineKernel.KernelModules[i6] != nil {
						cp.MachineConfig.MachineKernel.KernelModules[i6] = new(KernelModuleConfig)
						*cp.MachineConfig.MachineKernel.KernelModules[i6] = *o.MachineConfig.MachineKernel.KernelModules[i6]
						if o.MachineConfig.MachineKernel.KernelModules[i6].ModuleParameters != nil {
							cp.MachineConfig.MachineKernel.KernelModules[i6].ModuleParameters = make([]string, len(o.MachineConfig.MachineKernel.KernelModules[i6].ModuleParameters))
							copy(cp.MachineConfig.MachineKernel.KernelModules[i6].ModuleParameters, o.MachineConfig.MachineKernel.KernelModules[i6].ModuleParameters)
						}
					}
				}
			}
		}
		if o.MachineConfig.MachineSeccompProfiles != nil {
			cp.MachineConfig.MachineSeccompProfiles = make([]*MachineSeccompProfile, len(o.MachineConfig.MachineSeccompProfiles))
			copy(cp.MachineConfig.MachineSeccompProfiles, o.MachineConfig.MachineSeccompProfiles)
			for i4 := range o.MachineConfig.MachineSeccompProfiles {
				if o.MachineConfig.MachineSeccompProfiles[i4] != nil {
					cp.MachineConfig.MachineSeccompProfiles[i4] = new(MachineSeccompProfile)
					*cp.MachineConfig.MachineSeccompProfiles[i4] = *o.MachineConfig.MachineSeccompProfiles[i4]
					{
						retV := o.MachineConfig.MachineSeccompProfiles[i4].MachineSeccompProfileValue.DeepCopy()
						cp.MachineConfig.MachineSeccompProfiles[i4].MachineSeccompProfileValue = *retV
					}
				}
			}
		}
		{
			retV := o.MachineConfig.MachineBaseRuntimeSpecOverrides.DeepCopy()
			cp.MachineConfig.MachineBaseRuntimeSpecOverrides = *retV
		}
		if o.MachineConfig.MachineNodeLabels != nil {
			cp.MachineConfig.MachineNodeLabels = make(map[string]string, len(o.MachineConfig.MachineNodeLabels))
			for k4, v4 := range o.MachineConfig.MachineNodeLabels {
				cp.MachineConfig.MachineNodeLabels[k4] = v4
			}
		}
		if o.MachineConfig.MachineNodeAnnotations != nil {
			cp.MachineConfig.MachineNodeAnnotations = make(map[string]string, len(o.MachineConfig.MachineNodeAnnotations))
			for k4, v4 := range o.MachineConfig.MachineNodeAnnotations {
				cp.MachineConfig.MachineNodeAnnotations[k4] = v4
			}
		}
		if o.MachineConfig.MachineNodeTaints != nil {
			cp.MachineConfig.MachineNodeTaints = make(map[string]string, len(o.MachineConfig.MachineNodeTaints))
			for k4, v4 := range o.MachineConfig.MachineNodeTaints {
				cp.MachineConfig.MachineNodeTaints[k4] = v4
			}
		}
	}
	if o.ClusterConfig != nil {
		cp.ClusterConfig = new(ClusterConfig)
		*cp.ClusterConfig = *o.ClusterConfig
		if o.ClusterConfig.ControlPlane != nil {
			cp.ClusterConfig.ControlPlane = new(ControlPlaneConfig)
			*cp.ClusterConfig.ControlPlane = *o.ClusterConfig.ControlPlane
			if o.ClusterConfig.ControlPlane.Endpoint != nil {
				cp.ClusterConfig.ControlPlane.Endpoint = o.ClusterConfig.ControlPlane.Endpoint.DeepCopy()
			}
		}
		if o.ClusterConfig.ClusterNetwork != nil {
			cp.ClusterConfig.ClusterNetwork = new(ClusterNetworkConfig)
			*cp.ClusterConfig.ClusterNetwork = *o.ClusterConfig.ClusterNetwork
			if o.ClusterConfig.ClusterNetwork.CNI != nil {
				cp.ClusterConfig.ClusterNetwork.CNI = new(CNIConfig)
				*cp.ClusterConfig.ClusterNetwork.CNI = *o.ClusterConfig.ClusterNetwork.CNI
				if o.ClusterConfig.ClusterNetwork.CNI.CNIUrls != nil {
					cp.ClusterConfig.ClusterNetwork.CNI.CNIUrls = make([]string, len(o.ClusterConfig.ClusterNetwork.CNI.CNIUrls))
					copy(cp.ClusterConfig.ClusterNetwork.CNI.CNIUrls, o.ClusterConfig.ClusterNetwork.CNI.CNIUrls)
				}
				if o.ClusterConfig.ClusterNetwork.CNI.CNIFlannel != nil {
					cp.ClusterConfig.ClusterNetwork.CNI.CNIFlannel = new(FlannelCNIConfig)
					*cp.ClusterConfig.ClusterNetwork.CNI.CNIFlannel = *o.ClusterConfig.ClusterNetwork.CNI.CNIFlannel
					if o.ClusterConfig.ClusterNetwork.CNI.CNIFlannel.FlanneldExtraArgs != nil {
						cp.ClusterConfig.ClusterNetwork.CNI.CNIFlannel.FlanneldExtraArgs = make([]string, len(o.ClusterConfig.ClusterNetwork.CNI.CNIFlannel.FlanneldExtraArgs))
						copy(cp.ClusterConfig.ClusterNetwork.CNI.CNIFlannel.FlanneldExtraArgs, o.ClusterConfig.ClusterNetwork.CNI.CNIFlannel.FlanneldExtraArgs)
					}
				}
			}
			if o.ClusterConfig.ClusterNetwork.PodSubnet != nil {
				cp.ClusterConfig.ClusterNetwork.PodSubnet = make([]string, len(o.ClusterConfig.ClusterNetwork.PodSubnet))
				copy(cp.ClusterConfig.ClusterNetwork.PodSubnet, o.ClusterConfig.ClusterNetwork.PodSubnet)
			}
			if o.ClusterConfig.ClusterNetwork.ServiceSubnet != nil {
				cp.ClusterConfig.ClusterNetwork.ServiceSubnet = make([]string, len(o.ClusterConfig.ClusterNetwork.ServiceSubnet))
				copy(cp.ClusterConfig.ClusterNetwork.ServiceSubnet, o.ClusterConfig.ClusterNetwork.ServiceSubnet)
			}
		}
		if o.ClusterConfig.ClusterCA != nil {
			cp.ClusterConfig.ClusterCA = o.ClusterConfig.ClusterCA.DeepCopy()
		}
		if o.ClusterConfig.ClusterAcceptedCAs != nil {
			cp.ClusterConfig.ClusterAcceptedCAs = make([]*x509.PEMEncodedCertificate, len(o.ClusterConfig.ClusterAcceptedCAs))
			copy(cp.ClusterConfig.ClusterAcceptedCAs, o.ClusterConfig.ClusterAcceptedCAs)
			for i4 := range o.ClusterConfig.ClusterAcceptedCAs {
				if o.ClusterConfig.ClusterAcceptedCAs[i4] != nil {
					cp.ClusterConfig.ClusterAcceptedCAs[i4] = o.ClusterConfig.ClusterAcceptedCAs[i4].DeepCopy()
				}
			}
		}
		if o.ClusterConfig.ClusterAggregatorCA != nil {
			cp.ClusterConfig.ClusterAggregatorCA = o.ClusterConfig.ClusterAggregatorCA.DeepCopy()
		}
		if o.ClusterConfig.ClusterServiceAccount != nil {
			cp.ClusterConfig.ClusterServiceAccount = o.ClusterConfig.ClusterServiceAccount.DeepCopy()
		}
		if o.ClusterConfig.APIServerConfig != nil {
			cp.ClusterConfig.APIServerConfig = new(APIServerConfig)
			*cp.ClusterConfig.APIServerConfig = *o.ClusterConfig.APIServerConfig
			if o.ClusterConfig.APIServerConfig.ExtraArgsConfig != nil {
				cp.ClusterConfig.APIServerConfig.ExtraArgsConfig = make(map[string]ArgValue, len(o.ClusterConfig.APIServerConfig.ExtraArgsConfig))
				for k6, v6 := range o.ClusterConfig.APIServerConfig.ExtraArgsConfig {
					var cp_ClusterConfig_APIServerConfig_ExtraArgsConfig_v6 ArgValue
					{
						retV := v6.DeepCopy()
						cp_ClusterConfig_APIServerConfig_ExtraArgsConfig_v6 = *retV
					}
					cp.ClusterConfig.APIServerConfig.ExtraArgsConfig[k6] = cp_ClusterConfig_APIServerConfig_ExtraArgsConfig_v6
				}
			}
			if o.ClusterConfig.APIServerConfig.ExtraVolumesConfig != nil {
				cp.ClusterConfig.APIServerConfig.ExtraVolumesConfig = make([]VolumeMountConfig, len(o.ClusterConfig.APIServerConfig.ExtraVolumesConfig))
				copy(cp.ClusterConfig.APIServerConfig.ExtraVolumesConfig, o.ClusterConfig.APIServerConfig.ExtraVolumesConfig)
			}
			if o.ClusterConfig.APIServerConfig.EnvConfig != nil {
				cp.ClusterConfig.APIServerConfig.EnvConfig = make(map[string]string, len(o.ClusterConfig.APIServerConfig.EnvConfig))
				for k6, v6 := range o.ClusterConfig.APIServerConfig.EnvConfig {
					cp.ClusterConfig.APIServerConfig.EnvConfig[k6] = v6
				}
			}
			if o.ClusterConfig.APIServerConfig.CertSANs != nil {
				cp.ClusterConfig.APIServerConfig.CertSANs = make([]string, len(o.ClusterConfig.APIServerConfig.CertSANs))
				copy(cp.ClusterConfig.APIServerConfig.CertSANs, o.ClusterConfig.APIServerConfig.CertSANs)
			}
			if o.ClusterConfig.APIServerConfig.DisablePodSecurityPolicyConfig != nil {
				cp.ClusterConfig.APIServerConfig.DisablePodSecurityPolicyConfig = new(bool)
				*cp.ClusterConfig.APIServerConfig.DisablePodSecurityPolicyConfig = *o.ClusterConfig.APIServerConfig.DisablePodSecurityPolicyConfig
			}
			if o.ClusterConfig.APIServerConfig.AdmissionControlConfig != nil {
				cp.ClusterConfig.APIServerConfig.AdmissionControlConfig = make([]*AdmissionPluginConfig, len(o.ClusterConfig.APIServerConfig.AdmissionControlConfig))
				copy(cp.ClusterConfig.APIServerConfig.AdmissionControlConfig, o.ClusterConfig.APIServerConfig.AdmissionControlConfig)
				for i6 := range o.ClusterConfig.APIServerConfig.AdmissionControlConfig {
					if o.ClusterConfig.APIServerConfig.AdmissionControlConfig[i6] != nil {
						cp.ClusterConfig.APIServerConfig.AdmissionControlConfig[i6] = new(AdmissionPluginConfig)
						*cp.ClusterConfig.APIServerConfig.AdmissionControlConfig[i6] = *o.ClusterConfig.APIServerConfig.AdmissionControlConfig[i6]
						{
							retV := o.ClusterConfig.APIServerConfig.AdmissionControlConfig[i6].PluginConfiguration.DeepCopy()
							cp.ClusterConfig.APIServerConfig.AdmissionControlConfig[i6].PluginConfiguration = *retV
						}
					}
				}
			}
			{
				retV := o.ClusterConfig.APIServerConfig.AuditPolicyConfig.DeepCopy()
				cp.ClusterConfig.APIServerConfig.AuditPolicyConfig = *retV
			}
			if o.ClusterConfig.APIServerConfig.ResourcesConfig != nil {
				cp.ClusterConfig.APIServerConfig.ResourcesConfig = new(ResourcesConfig)
				*cp.ClusterConfig.APIServerConfig.ResourcesConfig = *o.ClusterConfig.APIServerConfig.ResourcesConfig
				{
					retV := o.ClusterConfig.APIServerConfig.ResourcesConfig.Requests.DeepCopy()
					cp.ClusterConfig.APIServerConfig.ResourcesConfig.Requests = *retV
				}
				{
					retV := o.ClusterConfig.APIServerConfig.ResourcesConfig.Limits.DeepCopy()
					cp.ClusterConfig.APIServerConfig.ResourcesConfig.Limits = *retV
				}
			}
			if o.ClusterConfig.APIServerConfig.AuthorizationConfigConfig != nil {
				cp.ClusterConfig.APIServerConfig.AuthorizationConfigConfig = make([]*AuthorizationConfigAuthorizerConfig, len(o.ClusterConfig.APIServerConfig.AuthorizationConfigConfig))
				copy(cp.ClusterConfig.APIServerConfig.AuthorizationConfigConfig, o.ClusterConfig.APIServerConfig.AuthorizationConfigConfig)
				for i6 := range o.ClusterConfig.APIServerConfig.AuthorizationConfigConfig {
					if o.ClusterConfig.APIServerConfig.AuthorizationConfigConfig[i6] != nil {
						cp.ClusterConfig.APIServerConfig.AuthorizationConfigConfig[i6] = new(AuthorizationConfigAuthorizerConfig)
						*cp.ClusterConfig.APIServerConfig.AuthorizationConfigConfig[i6] = *o.ClusterConfig.APIServerConfig.AuthorizationConfigConfig[i6]
						{
							retV := o.ClusterConfig.APIServerConfig.AuthorizationConfigConfig[i6].AuthorizerWebhook.DeepCopy()
							cp.ClusterConfig.APIServerConfig.AuthorizationConfigConfig[i6].AuthorizerWebhook = *retV
						}
					}
				}
			}
		}
		if o.ClusterConfig.ControllerManagerConfig != nil {
			cp.ClusterConfig.ControllerManagerConfig = new(ControllerManagerConfig)
			*cp.ClusterConfig.ControllerManagerConfig = *o.ClusterConfig.ControllerManagerConfig
			if o.ClusterConfig.ControllerManagerConfig.ExtraArgsConfig != nil {
				cp.ClusterConfig.ControllerManagerConfig.ExtraArgsConfig = make(map[string]ArgValue, len(o.ClusterConfig.ControllerManagerConfig.ExtraArgsConfig))
				for k6, v6 := range o.ClusterConfig.ControllerManagerConfig.ExtraArgsConfig {
					var cp_ClusterConfig_ControllerManagerConfig_ExtraArgsConfig_v6 ArgValue
					{
						retV := v6.DeepCopy()
						cp_ClusterConfig_ControllerManagerConfig_ExtraArgsConfig_v6 = *retV
					}
					cp.ClusterConfig.ControllerManagerConfig.ExtraArgsConfig[k6] = cp_ClusterConfig_ControllerManagerConfig_ExtraArgsConfig_v6
				}
			}
			if o.ClusterConfig.ControllerManagerConfig.ExtraVolumesConfig != nil {
				cp.ClusterConfig.ControllerManagerConfig.ExtraVolumesConfig = make([]VolumeMountConfig, len(o.ClusterConfig.ControllerManagerConfig.ExtraVolumesConfig))
				copy(cp.ClusterConfig.ControllerManagerConfig.ExtraVolumesConfig, o.ClusterConfig.ControllerManagerConfig.ExtraVolumesConfig)
			}
			if o.ClusterConfig.ControllerManagerConfig.EnvConfig != nil {
				cp.ClusterConfig.ControllerManagerConfig.EnvConfig = make(map[string]string, len(o.ClusterConfig.ControllerManagerConfig.EnvConfig))
				for k6, v6 := range o.ClusterConfig.ControllerManagerConfig.EnvConfig {
					cp.ClusterConfig.ControllerManagerConfig.EnvConfig[k6] = v6
				}
			}
			if o.ClusterConfig.ControllerManagerConfig.ResourcesConfig != nil {
				cp.ClusterConfig.ControllerManagerConfig.ResourcesConfig = new(ResourcesConfig)
				*cp.ClusterConfig.ControllerManagerConfig.ResourcesConfig = *o.ClusterConfig.ControllerManagerConfig.ResourcesConfig
				{
					retV := o.ClusterConfig.ControllerManagerConfig.ResourcesConfig.Requests.DeepCopy()
					cp.ClusterConfig.ControllerManagerConfig.ResourcesConfig.Requests = *retV
				}
				{
					retV := o.ClusterConfig.ControllerManagerConfig.ResourcesConfig.Limits.DeepCopy()
					cp.ClusterConfig.ControllerManagerConfig.ResourcesConfig.Limits = *retV
				}
			}
		}
		if o.ClusterConfig.ProxyConfig != nil {
			cp.ClusterConfig.ProxyConfig = new(ProxyConfig)
			*cp.ClusterConfig.ProxyConfig = *o.ClusterConfig.ProxyConfig
			if o.ClusterConfig.ProxyConfig.Disabled != nil {
				cp.ClusterConfig.ProxyConfig.Disabled = new(bool)
				*cp.ClusterConfig.ProxyConfig.Disabled = *o.ClusterConfig.ProxyConfig.Disabled
			}
			if o.ClusterConfig.ProxyConfig.ExtraArgsConfig != nil {
				cp.ClusterConfig.ProxyConfig.ExtraArgsConfig = make(map[string]ArgValue, len(o.ClusterConfig.ProxyConfig.ExtraArgsConfig))
				for k6, v6 := range o.ClusterConfig.ProxyConfig.ExtraArgsConfig {
					var cp_ClusterConfig_ProxyConfig_ExtraArgsConfig_v6 ArgValue
					{
						retV := v6.DeepCopy()
						cp_ClusterConfig_ProxyConfig_ExtraArgsConfig_v6 = *retV
					}
					cp.ClusterConfig.ProxyConfig.ExtraArgsConfig[k6] = cp_ClusterConfig_ProxyConfig_ExtraArgsConfig_v6
				}
			}
		}
		if o.ClusterConfig.SchedulerConfig != nil {
			cp.ClusterConfig.SchedulerConfig = new(SchedulerConfig)
			*cp.ClusterConfig.SchedulerConfig = *o.ClusterConfig.SchedulerConfig
			if o.ClusterConfig.SchedulerConfig.ExtraArgsConfig != nil {
				cp.ClusterConfig.SchedulerConfig.ExtraArgsConfig = make(map[string]ArgValue, len(o.ClusterConfig.SchedulerConfig.ExtraArgsConfig))
				for k6, v6 := range o.ClusterConfig.SchedulerConfig.ExtraArgsConfig {
					var cp_ClusterConfig_SchedulerConfig_ExtraArgsConfig_v6 ArgValue
					{
						retV := v6.DeepCopy()
						cp_ClusterConfig_SchedulerConfig_ExtraArgsConfig_v6 = *retV
					}
					cp.ClusterConfig.SchedulerConfig.ExtraArgsConfig[k6] = cp_ClusterConfig_SchedulerConfig_ExtraArgsConfig_v6
				}
			}
			if o.ClusterConfig.SchedulerConfig.ExtraVolumesConfig != nil {
				cp.ClusterConfig.SchedulerConfig.ExtraVolumesConfig = make([]VolumeMountConfig, len(o.ClusterConfig.SchedulerConfig.ExtraVolumesConfig))
				copy(cp.ClusterConfig.SchedulerConfig.ExtraVolumesConfig, o.ClusterConfig.SchedulerConfig.ExtraVolumesConfig)
			}
			if o.ClusterConfig.SchedulerConfig.EnvConfig != nil {
				cp.ClusterConfig.SchedulerConfig.EnvConfig = make(map[string]string, len(o.ClusterConfig.SchedulerConfig.EnvConfig))
				for k6, v6 := range o.ClusterConfig.SchedulerConfig.EnvConfig {
					cp.ClusterConfig.SchedulerConfig.EnvConfig[k6] = v6
				}
			}
			if o.ClusterConfig.SchedulerConfig.ResourcesConfig != nil {
				cp.ClusterConfig.SchedulerConfig.ResourcesConfig = new(ResourcesConfig)
				*cp.ClusterConfig.SchedulerConfig.ResourcesConfig = *o.ClusterConfig.SchedulerConfig.ResourcesConfig
				{
					retV := o.ClusterConfig.SchedulerConfig.ResourcesConfig.Requests.DeepCopy()
					cp.ClusterConfig.SchedulerConfig.ResourcesConfig.Requests = *retV
				}
				{
					retV := o.ClusterConfig.SchedulerConfig.ResourcesConfig.Limits.DeepCopy()
					cp.ClusterConfig.SchedulerConfig.ResourcesConfig.Limits = *retV
				}
			}
			{
				retV := o.ClusterConfig.SchedulerConfig.SchedulerConfig.DeepCopy()
				cp.ClusterConfig.SchedulerConfig.SchedulerConfig = *retV
			}
		}
		if o.ClusterConfig.ClusterDiscoveryConfig != nil {
			cp.ClusterConfig.ClusterDiscoveryConfig = new(ClusterDiscoveryConfig)
			*cp.ClusterConfig.ClusterDiscoveryConfig = *o.ClusterConfig.ClusterDiscoveryConfig
			if o.ClusterConfig.ClusterDiscoveryConfig.DiscoveryEnabled != nil {
				cp.ClusterConfig.ClusterDiscoveryConfig.DiscoveryEnabled = new(bool)
				*cp.ClusterConfig.ClusterDiscoveryConfig.DiscoveryEnabled = *o.ClusterConfig.ClusterDiscoveryConfig.DiscoveryEnabled
			}
			if o.ClusterConfig.ClusterDiscoveryConfig.DiscoveryRegistries.RegistryKubernetes.RegistryDisabled != nil {
				cp.ClusterConfig.ClusterDiscoveryConfig.DiscoveryRegistries.RegistryKubernetes.RegistryDisabled = new(bool)
				*cp.ClusterConfig.ClusterDiscoveryConfig.DiscoveryRegistries.RegistryKubernetes.RegistryDisabled = *o.ClusterConfig.ClusterDiscoveryConfig.DiscoveryRegistries.RegistryKubernetes.RegistryDisabled
			}
			if o.ClusterConfig.ClusterDiscoveryConfig.DiscoveryRegistries.RegistryService.RegistryDisabled != nil {
				cp.ClusterConfig.ClusterDiscoveryConfig.DiscoveryRegistries.RegistryService.RegistryDisabled = new(bool)
				*cp.ClusterConfig.ClusterDiscoveryConfig.DiscoveryRegistries.RegistryService.RegistryDisabled = *o.ClusterConfig.ClusterDiscoveryConfig.DiscoveryRegistries.RegistryService.RegistryDisabled
			}
		}
		if o.ClusterConfig.EtcdConfig != nil {
			cp.ClusterConfig.EtcdConfig = new(EtcdConfig)
			*cp.ClusterConfig.EtcdConfig = *o.ClusterConfig.EtcdConfig
			if o.ClusterConfig.EtcdConfig.RootCA != nil {
				cp.ClusterConfig.EtcdConfig.RootCA = o.ClusterConfig.EtcdConfig.RootCA.DeepCopy()
			}
			if o.ClusterConfig.EtcdConfig.EtcdExtraArgs != nil {
				cp.ClusterConfig.EtcdConfig.EtcdExtraArgs = make(map[string]ArgValue, len(o.ClusterConfig.EtcdConfig.EtcdExtraArgs))
				for k6, v6 := range o.ClusterConfig.EtcdConfig.EtcdExtraArgs {
					var cp_ClusterConfig_EtcdConfig_EtcdExtraArgs_v6 ArgValue
					{
						retV := v6.DeepCopy()
						cp_ClusterConfig_EtcdConfig_EtcdExtraArgs_v6 = *retV
					}
					cp.ClusterConfig.EtcdConfig.EtcdExtraArgs[k6] = cp_ClusterConfig_EtcdConfig_EtcdExtraArgs_v6
				}
			}
			if o.ClusterConfig.EtcdConfig.EtcdAdvertisedSubnets != nil {
				cp.ClusterConfig.EtcdConfig.EtcdAdvertisedSubnets = make([]string, len(o.ClusterConfig.EtcdConfig.EtcdAdvertisedSubnets))
				copy(cp.ClusterConfig.EtcdConfig.EtcdAdvertisedSubnets, o.ClusterConfig.EtcdConfig.EtcdAdvertisedSubnets)
			}
			if o.ClusterConfig.EtcdConfig.EtcdListenSubnets != nil {
				cp.ClusterConfig.EtcdConfig.EtcdListenSubnets = make([]string, len(o.ClusterConfig.EtcdConfig.EtcdListenSubnets))
				copy(cp.ClusterConfig.EtcdConfig.EtcdListenSubnets, o.ClusterConfig.EtcdConfig.EtcdListenSubnets)
			}
		}
		if o.ClusterConfig.CoreDNSConfig != nil {
			cp.ClusterConfig.CoreDNSConfig = new(CoreDNS)
			*cp.ClusterConfig.CoreDNSConfig = *o.ClusterConfig.CoreDNSConfig
			if o.ClusterConfig.CoreDNSConfig.CoreDNSDisabled != nil {
				cp.ClusterConfig.CoreDNSConfig.CoreDNSDisabled = new(bool)
				*cp.ClusterConfig.CoreDNSConfig.CoreDNSDisabled = *o.ClusterConfig.CoreDNSConfig.CoreDNSDisabled
			}
		}
		if o.ClusterConfig.ExternalCloudProviderConfig != nil {
			cp.ClusterConfig.ExternalCloudProviderConfig = new(ExternalCloudProviderConfig)
			*cp.ClusterConfig.ExternalCloudProviderConfig = *o.ClusterConfig.ExternalCloudProviderConfig
			if o.ClusterConfig.ExternalCloudProviderConfig.ExternalEnabled != nil {
				cp.ClusterConfig.ExternalCloudProviderConfig.ExternalEnabled = new(bool)
				*cp.ClusterConfig.ExternalCloudProviderConfig.ExternalEnabled = *o.ClusterConfig.ExternalCloudProviderConfig.ExternalEnabled
			}
			if o.ClusterConfig.ExternalCloudProviderConfig.ExternalManifests != nil {
				cp.ClusterConfig.ExternalCloudProviderConfig.ExternalManifests = make([]string, len(o.ClusterConfig.ExternalCloudProviderConfig.ExternalManifests))
				copy(cp.ClusterConfig.ExternalCloudProviderConfig.ExternalManifests, o.ClusterConfig.ExternalCloudProviderConfig.ExternalManifests)
			}
		}
		if o.ClusterConfig.ExtraManifests != nil {
			cp.ClusterConfig.ExtraManifests = make([]string, len(o.ClusterConfig.ExtraManifests))
			copy(cp.ClusterConfig.ExtraManifests, o.ClusterConfig.ExtraManifests)
		}
		if o.ClusterConfig.ExtraManifestHeaders != nil {
			cp.ClusterConfig.ExtraManifestHeaders = make(map[string]string, len(o.ClusterConfig.ExtraManifestHeaders))
			for k4, v4 := range o.ClusterConfig.ExtraManifestHeaders {
				cp.ClusterConfig.ExtraManifestHeaders[k4] = v4
			}
		}
		if o.ClusterConfig.ClusterInlineManifests != nil {
			cp.ClusterConfig.ClusterInlineManifests = make([]ClusterInlineManifest, len(o.ClusterConfig.ClusterInlineManifests))
			copy(cp.ClusterConfig.ClusterInlineManifests, o.ClusterConfig.ClusterInlineManifests)
		}
		if o.ClusterConfig.AdminKubeconfigConfig != nil {
			cp.ClusterConfig.AdminKubeconfigConfig = new(AdminKubeconfigConfig)
			*cp.ClusterConfig.AdminKubeconfigConfig = *o.ClusterConfig.AdminKubeconfigConfig
		}
		if o.ClusterConfig.AllowSchedulingOnMasters != nil {
			cp.ClusterConfig.AllowSchedulingOnMasters = new(bool)
			*cp.ClusterConfig.AllowSchedulingOnMasters = *o.ClusterConfig.AllowSchedulingOnMasters
		}
		if o.ClusterConfig.AllowSchedulingOnControlPlanes != nil {
			cp.ClusterConfig.AllowSchedulingOnControlPlanes = new(bool)
			*cp.ClusterConfig.AllowSchedulingOnControlPlanes = *o.ClusterConfig.AllowSchedulingOnControlPlanes
		}
	}
	return &cp
}

// DeepCopy generates a deep copy of *Device.
func (o *Device) DeepCopy() *Device {
	var cp Device = *o
	if o.DeviceSelector != nil {
		cp.DeviceSelector = new(NetworkDeviceSelector)
		*cp.DeviceSelector = *o.DeviceSelector
		if o.DeviceSelector.NetworkDevicePhysical != nil {
			cp.DeviceSelector.NetworkDevicePhysical = new(bool)
			*cp.DeviceSelector.NetworkDevicePhysical = *o.DeviceSelector.NetworkDevicePhysical
		}
	}
	if o.DeviceAddresses != nil {
		cp.DeviceAddresses = make([]string, len(o.DeviceAddresses))
		copy(cp.DeviceAddresses, o.DeviceAddresses)
	}
	if o.DeviceRoutes != nil {
		cp.DeviceRoutes = make([]*Route, len(o.DeviceRoutes))
		copy(cp.DeviceRoutes, o.DeviceRoutes)
		for i2 := range o.DeviceRoutes {
			if o.DeviceRoutes[i2] != nil {
				cp.DeviceRoutes[i2] = new(Route)
				*cp.DeviceRoutes[i2] = *o.DeviceRoutes[i2]
			}
		}
	}
	if o.DeviceBond != nil {
		cp.DeviceBond = new(Bond)
		*cp.DeviceBond = *o.DeviceBond
		if o.DeviceBond.BondInterfaces != nil {
			cp.DeviceBond.BondInterfaces = make([]string, len(o.DeviceBond.BondInterfaces))
			copy(cp.DeviceBond.BondInterfaces, o.DeviceBond.BondInterfaces)
		}
		if o.DeviceBond.BondDeviceSelectors != nil {
			cp.DeviceBond.BondDeviceSelectors = make([]NetworkDeviceSelector, len(o.DeviceBond.BondDeviceSelectors))
			copy(cp.DeviceBond.BondDeviceSelectors, o.DeviceBond.BondDeviceSelectors)
			for i4 := range o.DeviceBond.BondDeviceSelectors {
				if o.DeviceBond.BondDeviceSelectors[i4].NetworkDevicePhysical != nil {
					cp.DeviceBond.BondDeviceSelectors[i4].NetworkDevicePhysical = new(bool)
					*cp.DeviceBond.BondDeviceSelectors[i4].NetworkDevicePhysical = *o.DeviceBond.BondDeviceSelectors[i4].NetworkDevicePhysical
				}
			}
		}
		if o.DeviceBond.BondARPIPTarget != nil {
			cp.DeviceBond.BondARPIPTarget = make([]string, len(o.DeviceBond.BondARPIPTarget))
			copy(cp.DeviceBond.BondARPIPTarget, o.DeviceBond.BondARPIPTarget)
		}
		if o.DeviceBond.BondUseCarrier != nil {
			cp.DeviceBond.BondUseCarrier = new(bool)
			*cp.DeviceBond.BondUseCarrier = *o.DeviceBond.BondUseCarrier
		}
	}
	if o.DeviceBridge != nil {
		cp.DeviceBridge = new(Bridge)
		*cp.DeviceBridge = *o.DeviceBridge
		if o.DeviceBridge.BridgedInterfaces != nil {
			cp.DeviceBridge.BridgedInterfaces = make([]string, len(o.DeviceBridge.BridgedInterfaces))
			copy(cp.DeviceBridge.BridgedInterfaces, o.DeviceBridge.BridgedInterfaces)
		}
		if o.DeviceBridge.BridgeSTP != nil {
			cp.DeviceBridge.BridgeSTP = new(STP)
			*cp.DeviceBridge.BridgeSTP = *o.DeviceBridge.BridgeSTP
			if o.DeviceBridge.BridgeSTP.STPEnabled != nil {
				cp.DeviceBridge.BridgeSTP.STPEnabled = new(bool)
				*cp.DeviceBridge.BridgeSTP.STPEnabled = *o.DeviceBridge.BridgeSTP.STPEnabled
			}
		}
		if o.DeviceBridge.BridgeVLAN != nil {
			cp.DeviceBridge.BridgeVLAN = new(BridgeVLAN)
			*cp.DeviceBridge.BridgeVLAN = *o.DeviceBridge.BridgeVLAN
			if o.DeviceBridge.BridgeVLAN.BridgeVLANFiltering != nil {
				cp.DeviceBridge.BridgeVLAN.BridgeVLANFiltering = new(bool)
				*cp.DeviceBridge.BridgeVLAN.BridgeVLANFiltering = *o.DeviceBridge.BridgeVLAN.BridgeVLANFiltering
			}
		}
	}
	if o.DeviceBridgePort != nil {
		cp.DeviceBridgePort = new(BridgePort)
		*cp.DeviceBridgePort = *o.DeviceBridgePort
	}
	if o.DeviceVlans != nil {
		cp.DeviceVlans = make([]*Vlan, len(o.DeviceVlans))
		copy(cp.DeviceVlans, o.DeviceVlans)
		for i2 := range o.DeviceVlans {
			if o.DeviceVlans[i2] != nil {
				cp.DeviceVlans[i2] = new(Vlan)
				*cp.DeviceVlans[i2] = *o.DeviceVlans[i2]
				if o.DeviceVlans[i2].VlanAddresses != nil {
					cp.DeviceVlans[i2].VlanAddresses = make([]string, len(o.DeviceVlans[i2].VlanAddresses))
					copy(cp.DeviceVlans[i2].VlanAddresses, o.DeviceVlans[i2].VlanAddresses)
				}
				if o.DeviceVlans[i2].VlanRoutes != nil {
					cp.DeviceVlans[i2].VlanRoutes = make([]*Route, len(o.DeviceVlans[i2].VlanRoutes))
					copy(cp.DeviceVlans[i2].VlanRoutes, o.DeviceVlans[i2].VlanRoutes)
					for i5 := range o.DeviceVlans[i2].VlanRoutes {
						if o.DeviceVlans[i2].VlanRoutes[i5] != nil {
							cp.DeviceVlans[i2].VlanRoutes[i5] = new(Route)
							*cp.DeviceVlans[i2].VlanRoutes[i5] = *o.DeviceVlans[i2].VlanRoutes[i5]
						}
					}
				}
				if o.DeviceVlans[i2].VlanDHCP != nil {
					cp.DeviceVlans[i2].VlanDHCP = new(bool)
					*cp.DeviceVlans[i2].VlanDHCP = *o.DeviceVlans[i2].VlanDHCP
				}
				if o.DeviceVlans[i2].VlanVIP != nil {
					cp.DeviceVlans[i2].VlanVIP = new(DeviceVIPConfig)
					*cp.DeviceVlans[i2].VlanVIP = *o.DeviceVlans[i2].VlanVIP
					if o.DeviceVlans[i2].VlanVIP.EquinixMetalConfig != nil {
						cp.DeviceVlans[i2].VlanVIP.EquinixMetalConfig = new(VIPEquinixMetalConfig)
						*cp.DeviceVlans[i2].VlanVIP.EquinixMetalConfig = *o.DeviceVlans[i2].VlanVIP.EquinixMetalConfig
					}
					if o.DeviceVlans[i2].VlanVIP.HCloudConfig != nil {
						cp.DeviceVlans[i2].VlanVIP.HCloudConfig = new(VIPHCloudConfig)
						*cp.DeviceVlans[i2].VlanVIP.HCloudConfig = *o.DeviceVlans[i2].VlanVIP.HCloudConfig
					}
				}
				if o.DeviceVlans[i2].VlanDHCPOptions != nil {
					cp.DeviceVlans[i2].VlanDHCPOptions = new(DHCPOptions)
					*cp.DeviceVlans[i2].VlanDHCPOptions = *o.DeviceVlans[i2].VlanDHCPOptions
					if o.DeviceVlans[i2].VlanDHCPOptions.DHCPIPv4 != nil {
						cp.DeviceVlans[i2].VlanDHCPOptions.DHCPIPv4 = new(bool)
						*cp.DeviceVlans[i2].VlanDHCPOptions.DHCPIPv4 = *o.DeviceVlans[i2].VlanDHCPOptions.DHCPIPv4
					}
					if o.DeviceVlans[i2].VlanDHCPOptions.DHCPIPv6 != nil {
						cp.DeviceVlans[i2].VlanDHCPOptions.DHCPIPv6 = new(bool)
						*cp.DeviceVlans[i2].VlanDHCPOptions.DHCPIPv6 = *o.DeviceVlans[i2].VlanDHCPOptions.DHCPIPv6
					}
				}
			}
		}
	}
	if o.DeviceDHCP != nil {
		cp.DeviceDHCP = new(bool)
		*cp.DeviceDHCP = *o.DeviceDHCP
	}
	if o.DeviceIgnore != nil {
		cp.DeviceIgnore = new(bool)
		*cp.DeviceIgnore = *o.DeviceIgnore
	}
	if o.DeviceDummy != nil {
		cp.DeviceDummy = new(bool)
		*cp.DeviceDummy = *o.DeviceDummy
	}
	if o.DeviceDHCPOptions != nil {
		cp.DeviceDHCPOptions = new(DHCPOptions)
		*cp.DeviceDHCPOptions = *o.DeviceDHCPOptions
		if o.DeviceDHCPOptions.DHCPIPv4 != nil {
			cp.DeviceDHCPOptions.DHCPIPv4 = new(bool)
			*cp.DeviceDHCPOptions.DHCPIPv4 = *o.DeviceDHCPOptions.DHCPIPv4
		}
		if o.DeviceDHCPOptions.DHCPIPv6 != nil {
			cp.DeviceDHCPOptions.DHCPIPv6 = new(bool)
			*cp.DeviceDHCPOptions.DHCPIPv6 = *o.DeviceDHCPOptions.DHCPIPv6
		}
	}
	if o.DeviceWireguardConfig != nil {
		cp.DeviceWireguardConfig = new(DeviceWireguardConfig)
		*cp.DeviceWireguardConfig = *o.DeviceWireguardConfig
		if o.DeviceWireguardConfig.WireguardPeers != nil {
			cp.DeviceWireguardConfig.WireguardPeers = make([]*DeviceWireguardPeer, len(o.DeviceWireguardConfig.WireguardPeers))
			copy(cp.DeviceWireguardConfig.WireguardPeers, o.DeviceWireguardConfig.WireguardPeers)
			for i4 := range o.DeviceWireguardConfig.WireguardPeers {
				if o.DeviceWireguardConfig.WireguardPeers[i4] != nil {
					cp.DeviceWireguardConfig.WireguardPeers[i4] = new(DeviceWireguardPeer)
					*cp.DeviceWireguardConfig.WireguardPeers[i4] = *o.DeviceWireguardConfig.WireguardPeers[i4]
					if o.DeviceWireguardConfig.WireguardPeers[i4].WireguardAllowedIPs != nil {
						cp.DeviceWireguardConfig.WireguardPeers[i4].WireguardAllowedIPs = make([]string, len(o.DeviceWireguardConfig.WireguardPeers[i4].WireguardAllowedIPs))
						copy(cp.DeviceWireguardConfig.WireguardPeers[i4].WireguardAllowedIPs, o.DeviceWireguardConfig.WireguardPeers[i4].WireguardAllowedIPs)
					}
				}
			}
		}
	}
	if o.DeviceVIPConfig != nil {
		cp.DeviceVIPConfig = new(DeviceVIPConfig)
		*cp.DeviceVIPConfig = *o.DeviceVIPConfig
		if o.DeviceVIPConfig.EquinixMetalConfig != nil {
			cp.DeviceVIPConfig.EquinixMetalConfig = new(VIPEquinixMetalConfig)
			*cp.DeviceVIPConfig.EquinixMetalConfig = *o.DeviceVIPConfig.EquinixMetalConfig
		}
		if o.DeviceVIPConfig.HCloudConfig != nil {
			cp.DeviceVIPConfig.HCloudConfig = new(VIPHCloudConfig)
			*cp.DeviceVIPConfig.HCloudConfig = *o.DeviceVIPConfig.HCloudConfig
		}
	}
	return &cp
}

// DeepCopy generates a deep copy of *ArgValue.
func (o *ArgValue) DeepCopy() *ArgValue {
	var cp ArgValue = *o
	if o.listValue != nil {
		cp.listValue = make([]string, len(o.listValue))
		copy(cp.listValue, o.listValue)
	}
	return &cp
}
